setwd("/home/jin/Dropbox/Goh/Project_1/Slide_Jin")
p=c(0.02,0.9,0.08)
P_alpha<-p^10/sum(p^10)
pdf("escort_fig1.pdf")
a<-1
P_alpha<-round(p^a/sum(p^a),2)
names(P_alpha)<-c(1,2,3)
bar1=barplot(P_alpha,ylim=c(0,1), ylab="Escort probability",cex.axis = 2.5, cex.lab=1.5,cex.names=3)
legend("topright",expression(paste(alpha,"=1")),cex=4,box.col = 'transparent')
text(x = bar1, y = P_alpha, label = P_alpha, pos = 3, cex = 2, col = "red")
dev.off()
a<-0.5
pdf("escort_fig2.pdf")
P_alpha<-round(p^a/sum(p^a),2)
names(P_alpha)<-c(1,2,3)
bar2=barplot(P_alpha,ylim=c(0,1), ylab="Escort probability",cex.axis = 2.5, cex.lab=1.5,cex.names=3)
legend("topright",expression(paste(alpha,"=0.5")),cex=4,box.col = 'transparent')
text(x = bar2, y = P_alpha, label = P_alpha, pos = 3, cex = 2, col = "red")
dev.off()
a<-0.05
pdf("escort_fig3.pdf")
P_alpha<-round(p^a/sum(p^a),2)
names(P_alpha)<-c(1,2,3)
bar3 = barplot(P_alpha,ylim=c(0,1), ylab="Escort probability",cex.axis = 2.5, cex.lab=1.5,cex.names=3)
legend("topright",expression(paste(alpha,"=0.05")),cex=4,box.col = 'transparent')
text(x = bar3, y = P_alpha, label = P_alpha, pos = 3, cex = 2, col = "red")
dev.off()
