var CWCodecClass=function(){function b(){}b.prototype.encode=function(b,f){var c=new CWShapeParser;return'{"List":{"MemberData":[{"data":{'+c.getCommentsString(b)+","+c.getGraphicsString(b)+","+c.getDeletedString(f)+"}}]}}"};b.prototype.decode=function(b){var f=[],c=[],a=new CWShapeParser,l;try{l=CwZ.parseJSON(b)}catch(e){b=CWUtils.decompress(b),l=CwZ.parseJSON(b)}l=l.List.MemberData[0].data;var d=l.Comments;for(b=0;b<d.length;b++)f.push(a.parseComment(d[b]));d=l.Graphics;for(b=0;b<d.length;b++){var g=
d[b];g.Cmt=g.Cmt.split("!^!").join("\n");var k=null;g.R?k=a.parseRectangle(g):g.E?k=a.parseEllipse(g):g.A?k=a.parseArrow(g):g.S?k=a.parseLine(g):g.H?k=a.parseHighlight(g):g.F?k=a.parseFreehand(g):g.SHL&&(k=a.parseSelectionHL(g));f.push(k)}a=l.Deleted;for(b=0;b<a.length;b++)c.push(a[b]);return{comments:f,deleted:c}};return b}(),CWCodec=new CWCodecClass;
function CWShapeParser(){var b=function(c,a){a&&(c.ID=a.uId,c.color=translateCoordinate.convertColorSVG(a.Color),c.lineWidth=parseInt(a.LineWidth,10),c.page=parseInt(a.Page,10),c.ts=parseInt(a.TS,10),c.cmt=a.Cmt)},h=function(c,a){for(var b=c.split(","),e=[],d=0;d<b.length;d+=2)e.push(new CWPoint(b[d],b[d+1]));a&&(e=translateCoordinate.getSVGPoints(e));return e},f=function(c,a){var b="";a&&(c=translateCoordinate.getJSONPoints(c));for(var b=b+(c[0].x.toString()+","+c[0].y.toString()),e=1;e<c.length;e++)b+=
","+c[e].x.toString()+","+c[e].y.toString();return b};this.parseRectangle=function(c){var a=new CWRectangle;b(a,c);a.points=h(c.R,!0);return a};this.parseHighlight=function(c){var a=new CWHighlight;b(a,c);a.points=h(c.H,!0);return a};this.parseEllipse=function(c){var a=new CWEllipse;b(a,c);a.points=h(c.E,!0);return a};this.parseLine=function(c){var a=new CWLine;b(a,c);a.points=h(c.S,!1);return a};this.parseArrow=function(c){var a=new CWArrow;b(a,c);a.points=h(c.A,!1);return a};this.parseFreehand=
function(c){var a=new CWFreehand;b(a,c);a.points=h(c.F,!1);return a};this.parseSelectionHL=function(c){var a=new CWSelectionHL;b(a,c);a.rects=c.SHL;0<a.rects.length&&0===a.points.length&&a.points.push(new CWPoint(a.rects[0].x,a.rects[0].y));return a};this.parseComment=function(b){var a=new CWComment;a.ID=b.uId;a.page=parseInt(b.Page,10);a.ts=parseInt(b.ts,10);a.cmt=b.Cmnt;b=b.Pos.split(",");a.point=new CWPoint(b[0],b[1]);return a};this.getDeletedString=function(b){for(var a='"Deleted":[',f=0;f<b.length;f++)a+=
'"'+b[f]+'"',","!==a.charAt(a.length-1)&&(a+=",");","===a.charAt(a.length-1)&&(a=a.substr(0,a.length-1));return a+"]"};this.getGraphicsString=function(b){for(var a='"Graphics":[',h=0;h<b.length;h++){var e=b[h];if(!(e instanceof CWComment)){var d="";if(e instanceof CWFreehand)d+='{"F":"',d+=f(e.points,!1),d+='"';else if(e instanceof CWLine)d+='{"S":"',d+=f(e.points,!1),d+='"';else if(e instanceof CWArrow)d+='{"A":"',d+=f(e.points,!1),d+='"';else if(e instanceof CWEllipse)d+='{"E":"',d+=f(e.points,
!0),d+='"';else if(e instanceof CWRectangle)d+='{"R":"',d+=f(e.points,!0),d+='"';else if(e instanceof CWHighlight)d+='{"H":"',d+=f(e.points,!0),d+='"';else if(e instanceof CWSelectionHL){var d=d+'{"SHL":',g=e.rects,k="[";if(0<g.length)for(var k=k+('{"x":'+g[0].x+',"y":'+g[0].y+',"w":'+g[0].w+',"h":'+g[0].h+"}"),m=1;m<g.length;m++)k+=',{"x":'+g[m].x+',"y":'+g[m].y+',"w":'+g[m].w+',"h":'+g[m].h+"}";k+="]";d+=k}d+=',"Page":"'+e.page+'","Color":"'+translateCoordinate.convertColorJSON(e.color)+'","LineWidth":"'+
e.lineWidth.toString()+'","TS":"'+e.ts.toString()+'","Cmt":"'+e.cmt+'","uId":"'+e.ID+'"}';a+=d;","!==a.charAt(a.length-1)&&(a+=",")}}","===a.charAt(a.length-1)&&(a=a.substr(0,a.length-1));return a+"]"};this.getCommentsString=function(b){for(var a='"Comments":[',f=0;f<b.length;f++){var e=b[f];e instanceof CWComment&&(a+='{"Cmnt":"'+e.cmt+'","Pos":"'+e.point.x+","+e.point.y+'","Page":"'+e.page+'","ts":"'+e.ts+'","uId":"'+e.ID+'"}',","!==a.charAt(a.length-1)&&(a+=","))}","===a.charAt(a.length-1)&&(a=
a.substr(0,a.length-1));return a+"]"}}
var translateCoordinate={getSVGPoints:function(b){var h=[];if(2===b.length){var f=b[0];b=b[1];var c=new CWPoint;c.x=0<b.x?f.x+b.x:f.x-b.x;c.y=0<b.y?f.y+b.y:f.y-b.y;h.push(f);h.push(c)}return h},getJSONPoints:function(b){var h=[];if(2===b.length){var f=void 0,c=b[0],f=c;b=b[1];var a=new CWPoint;a.x=b.x>c.x?b.x-c.x:c.x-b.x;a.y=b.y>c.y?b.y-c.y:c.y-b.y;f.x=b.x<c.x?b.x:c.x;f.y=b.y<c.y?b.y:c.y;h.push(f);h.push(a)}return h},convertColorSVG:function(b){b=parseInt(b,10).toString(16);var h=b.length;if(6>h)for(var f=
0;f<6-h;f++)b="0"+b;return"#"+b},convertColorJSON:function(b){b=b.substr(1,b.length);return parseInt(b,16).toString()}};
