var CWUtilsClass=function(){function e(){this.isIframe=window!==window.parent;this.bParserTest=!1;this.browser={adobeAir:!1,ie:!1,ie9:!1,ie8:!1,ie7:!1,ie6:!1,chrome:!1,firefox:!1,opera:!1,safari:!1};this.sentry={};this.ajax={post:function(a,b,c,d){void 0===c&&(c=function(){});void 0===d&&(d=function(){});void 0===b&&(b={});CwZ.ajax({url:a,type:"POST",dataType:"text",data:b,success:c,error:d})},get:function(a,b,c,d){void 0===c&&(c=function(){});void 0===d&&(d=function(){});void 0===b&&(b={});CwZ.ajax({url:a,
type:"GET",dataType:"text",data:b,success:c,error:d})}}}e.prototype.removeTags=function(a){return a.replace(RegExp("(\\[(CSA|CrossRef|PubMed|Web of Science \u00ae|Taylor & Francis Online|Google Scholar)\\],?)","g"),"")};e.prototype.matchDoi=function(a){return a?(a=a.match(/\b(10[.][0-9]{4,}(?:[.][0-9]+)*\/(?:\S)+)/g))?a[0]:null:null};e.prototype.findDoi=function(a,b,c){a=CwZ(a).find("."+b).text();!a&&c&&(a=c);return CWUtils.matchDoi(a)};e.prototype.isValidURL=function(a){return/(ftp|http|https):\/\/(\w+:{0,1}\w*@)?(\S+)(:[0-9]+)?(\/|\/([\w#!:.?+=&%@!\-\/]))?/.test(a)?
!0:!1};e.prototype.getPageUrl=function(){return window.parent.location.href};e.prototype.getPageDomain=function(){var a=window.parent.location;return a.protocol+"//"+a.host};e.prototype.getDomainFromURL=function(a){a=a.replace(/^(.*\/\/)(.*?)(\/.*)$/,"$2");var b=/(.*?)(\w+)(\.[a-z]{2,3})(\.[a-z]{2})?$/;a.replace(b,"$1").replace(/\./g,"");return a=a.replace(b,"$2")};e.prototype.getQueryParam=function(a,b){void 0===b&&(b=location.search);a=a.replace(/[\[]/,"\\[").replace(/[\]]/,"\\]");var c=(new RegExp("[\\?&]"+
a+"=([^&#]*)")).exec(b);return null==c?"":decodeURIComponent(c[1].replace(/\+/g," "))};e.prototype.getFileTitle=function(a){var b=a.pdfLink,c=b.indexOf("#"),d=b.indexOf("?"),c=Math.min(0<c?c:b.length,0<d?d:b.length),b=b.substring(b.lastIndexOf("/",c)+1,c),c="";""!==a.identifier&&("number"===typeof a.identifier&&(a.identifier=a.identifier.toString()),c=a.identifier.replace(/[\\\/:\*\?\"<>|]/g,""));a="";a=0<=c.indexOf(b)?c:c+"_"+b;180<a.length&&(a=a.substr(0,180));return 0<=a.toLowerCase().indexOf(".pdf")?
a:a+".pdf"};e.prototype.updateScrollbar=function(a,b){CwZ(a).each(function(){var a=CwZ(this),d=!1;a.is(":visible")||(d=!0,a.show());d&&a.hide();b&&b(a)})};e.prototype.getEditDistance=function(a,b){if(0===a.length)return b.length;if(0===b.length)return a.length;var c=[],d;for(d=0;d<=b.length;d++)c[d]=[d];var f;for(f=0;f<=a.length;f++)c[0][f]=f;for(d=1;d<=b.length;d++)for(f=1;f<=a.length;f++)b.charAt(d-1)===a.charAt(f-1)?c[d][f]=c[d-1][f-1]:c[d][f]=Math.min(c[d-1][f-1]+1,Math.min(c[d][f-1]+1,c[d-1][f]+
1));return c[b.length][a.length]};e.prototype.moveScrollbarTo=function(a,b,c,d){void 0===c&&(c=!0);CwZ(a).each(function(){var a=CwZ(this);c?a.animate({scrollTop:b},400):a.scrollTop(parseInt(b,10))})};e.prototype.copyToClipboard=function(a){var b="INPUT"===a.tagName||"TEXTAREA"===a.tagName,c,d,f;b?(f=a,c=a.selectionStart,d=a.selectionEnd):(f=document.getElementById("_hiddenCopyText_"),f||(f=document.createElement("textarea"),f.style.position="absolute",f.style.left="-10000px",f.id="_hiddenCopyText_",
CwZ(a).append(f)),f.textContent=a.textContent);var e=document.activeElement;f.focus();f.setSelectionRange(0,f.value.length);var g;try{g=document.execCommand("copy")}catch(h){g=!1}e&&"function"===typeof e.focus&&e.focus();b?a.setSelectionRange(c,d):f.textContent="";return g};e.prototype.increaseProgress=function(){function a(){setTimeout(function(){if(CwZ("#cw-loader").is(":visible")){var b=CwZ("#cw-loader .cw-bar").width()/CwZ(".cw-progress").width()*100;CwZ("#cw-loader .cw-redirecting").hasClass("cw-hidden")&&
("undefined"!==typeof CWPDFReader_Publisher&&!CWPDFReader_Publisher.getInstance().progressComplete||"undefined"!==typeof CWPDFReader&&!CWPDFReader.progressComplete)&&(50>b?(CwZ(".cw-progress").addClass("cw-shine"),b+=12.5):75>b?b+=6.25:99>b+3?b+=3:99<b+3&&100!==b&&(b=99),CwZ("#cw-loader .cw-bar").width(b+"%"),CWUtils.log("progress: "+b),99>b&&a())}else CwZ("#cw-loader .cw-bar").width("0%")},1E3)}a()};e.prototype.moveScrollbarToXY=function(a,b,c){CwZ(a).each(function(){var a=CwZ(this),f=a.scrollTop(),
e=a.scrollLeft();a.scrollTop(f+-1*c,60);a.scrollLeft(e+-1*b,60)})};e.prototype.convertStrToBlob=function(a){var b;try{b=new Blob([a])}catch(c){window.BlobBuilder=window.BlobBuilder||window.WebKitBlobBuilder||window.MozBlobBuilder,b=new BlobBuilder,b.append(a),b=b.getBlob()}return b};e.prototype.log=function(a){a="object"===typeof a?a.message:a;CWPDFReaderConfig.debug&&this.browser.ie7&&(this.browser.ie8||this.browser.webkit)&&console.log("log:"+a)};e.prototype.generateEntLinks=function(a,b,c,d){"undefined"===
typeof d&&(d=!0);if("undefined"===typeof c||""===c)c=parseInt(a,16).toString().substring(0,3);c=function(a){switch(a){case "100":case "101":return"/profile";case "109":return"/publication";case "110":return"/publisher";case "111":return"/institute";case "161":return"/group";case "163":return"/journal";case "199":return"/author";default:return""}}(c);""===b.trim()&&(b=c.substring(1));d&&(c="/public"+c);return c+"/"+a+"/"+encodeURIComponent(b.toLowerCase().substring(0,500).trim().replace(/\s+/g,"_"))};
e.prototype.getAvatarColor=function(a){try{var b="#626be0 #e06277 #b467da #e09862 #1abc9c #f44336 #3498db #673ab7 #34495e #8bc24a #27ae60 #2980b9 #8e44ad #6c3244 #f1c40f #2266e6 #e74c3c #50e3c2 #4498ae #f39c12 #2c5e1c #ea1e63 #62b6e0 #484d9c".split(" "),c=" A B C D E F G H I J K L M N O P Q R S T U V W X Y Z".split(" "),d=c.slice();d.shift();var f="";c.forEach(function(c,e){d.forEach(function(d,e){a===c+d&&(f=b[e%b.length])})});return f}catch(e){return"#000000"}};e.prototype.trim=function(a){if(null==
a||void 0===a)a="";return CwZ.trim(a)};e.prototype.stripTags=function(a){return a=a.replace(/(<([^>]+)>)/ig,"")};e.prototype.timeDifference=function(a,b,c){void 0===b&&(b="Updated ");void 0===c&&(c="");a=new Date(a);var d=((new Date).getTime()-a.getTime())/1E3,f=Math.round(d/60),e=Math.round(f/60),g=Math.round(e/24),d=Math.round(d),f=Math.round(f),e=Math.round(e),g=Math.round(g);b=0<g?7<g?b+("JanFebMarAprMayJunJulAugSepOctNovDec".substr(3*a.getMonth(),3)+" "+a.getDate()+", "+a.getFullYear()):b+(g+
" day"+(1<g?"s":"")+" ago"):0<e?b+(e+" hour"+(1<e?"s":"")+" ago"):0<f?b+(f+" minute"+(1<f?"s":"")+" ago"):10>d?b+"Few secs ago":b+(d+" sec"+(1<d?"s":"")+" ago");return b+c};e.prototype.Compare=function(a,b){return a<=b+2&&a>=b-2};e.prototype.utf16to8=function(a){var b,c,d,f;b="";d=a.length;for(c=0;c<d;c++)f=a.charCodeAt(c),1<=f&&127>=f?b+=a.charAt(c):(2047<f?(b+=String.fromCharCode(224|f>>12&15),b+=String.fromCharCode(128|f>>6&63)):b+=String.fromCharCode(192|f>>6&31),b+=String.fromCharCode(128|f>>
0&63));return b};e.prototype.utf8to16=function(a){var b,c,d,f,e,g;b="";d=a.length;for(c=0;c<d;)switch(f=a.charCodeAt(c++),f>>4){case 0:case 1:case 2:case 3:case 4:case 5:case 6:case 7:b+=a.charAt(c-1);break;case 12:case 13:e=a.charCodeAt(c++);b+=String.fromCharCode((f&31)<<6|e&63);break;case 14:e=a.charCodeAt(c++),g=a.charCodeAt(c++),b+=String.fromCharCode((f&15)<<12|(e&63)<<6|(g&63)<<0)}return b};e.prototype.stringToByteArray=function(a){var b=new (void 0!==window.Uint8Array?Uint8Array:Array)(a.length),
c,d;c=0;for(d=a.length;c<d;++c)b[c]=a.charCodeAt(c)&255;return b};e.prototype.decompress=function(a){a=a.replace(/\n/g,"");a=a.replace(/ \/ /g,"/");a=atob(a);a=a.split("").map(function(a){return a.charCodeAt(0)});var b=(new Zlib.Gunzip(a)).decompress();a=[];for(var c=0;c<b.byteLength;c++)a.push(String.fromCharCode(b[c]));a=CWUtils.utf8to16(a.join(""));try{for(var d=JSON.parse(a),c=0;c<d.List.MemberData.length;c++){for(b=0;b<d.List.MemberData[c].data.Graphics.length;b++)if(!d.List.MemberData[c].data.Graphics[b].hasOwnProperty("SHL"))for(var f=
"AEFHRS".split(""),e=[],g=0;g<f.length;g++)if(d.List.MemberData[c].data.Graphics[b].hasOwnProperty(f[g])){for(var e=d.List.MemberData[c].data.Graphics[b][f[g]].split(","),h=0;h<e.length;h++)e[h]=Math.round(e[h]/2);d.List.MemberData[c].data.Graphics[b][f[g]]=e.join(",");break}for(b=0;b<d.List.MemberData[c].data.Comments.length;b++){for(var k=d.List.MemberData[c].data.Comments[b].Pos.split(","),f=0;f<k.length;f++)k[f]=Math.round(k[f]/2);d.List.MemberData[c].data.Comments[b].Pos=k.join(",")}a=JSON.stringify(d)}}catch(m){CWUtils.log(m)}return a};
e.prototype.compress=function(a){try{for(var b=JSON.parse(a),c=0;c<b.List.MemberData.length;c++){for(var d=0;d<b.List.MemberData[c].data.Graphics.length;d++)if(!b.List.MemberData[c].data.Graphics[d].hasOwnProperty("SHL"))for(var e="AEFHRS".split(""),l=[],g=0;g<e.length;g++)if(b.List.MemberData[c].data.Graphics[d].hasOwnProperty(e[g])){for(var l=b.List.MemberData[c].data.Graphics[d][e[g]].split(","),h=0;h<l.length;h++)l[h]=Math.round(2*l[h]);b.List.MemberData[c].data.Graphics[d][e[g]]=l.join(",");
break}for(d=0;d<b.List.MemberData[c].data.Comments.length;d++){for(var k=b.List.MemberData[c].data.Comments[d].Pos.split(","),e=0;e<k.length;e++)k[e]=Math.round(2*k[e]);b.List.MemberData[c].data.Comments[d].Pos=k.join(",")}a=JSON.stringify(b)}}catch(m){CWUtils.log(m)}c=CWUtils.stringToByteArray(CWUtils.utf16to8(a));a=(new Zlib.Gzip(c)).compress();b="";for(c=0;c<a.byteLength;c++)b+=String.fromCharCode(a[c]);b=btoa(b);return CWUtils.insertBN(b)};e.prototype.insertBN=function(a){for(var b="";0<a.length;){var c=
a.slice(0,76),b=b+c;76===c.length&&(b+="\n");a=a.replace(c,"")}return b};e.prototype.writeCookie=function(a,b,c){var d="";c&&(d=new Date,d.setTime(d.getTime()+864E5*c),d="; expires="+d.toGMTString());document.cookie=a+"="+b+d+"; path=/"};e.prototype.readCookie=function(a){a+="=";for(var b=document.cookie.split(";"),c=0;c<b.length;c++){for(var d=b[c];" "===d.charAt(0);)d=d.substring(1,d.length);if(0===d.indexOf(a))return d.substring(a.length,d.length)}return null};e.prototype.deleteCookie=function(a){this.writeCookie(a,
"",-1)};return e}(),Base64={_keyStr:"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=",encode:function(e){try{var a="",b=void 0,c=void 0,d=void 0,f=void 0,l=void 0,g=void 0,h=void 0,k=0;for(e=Base64._utf8_encode(e);k<e.length;)b=e.charCodeAt(k++),c=e.charCodeAt(k++),d=e.charCodeAt(k++),f=b>>2,l=(b&3)<<4|c>>4,g=(c&15)<<2|d>>6,h=d&63,isNaN(c)?g=h=64:isNaN(d)&&(h=64),a=a+this._keyStr.charAt(f)+this._keyStr.charAt(l)+this._keyStr.charAt(g)+this._keyStr.charAt(h);return a}catch(m){return""}},
decode:function(e){var a="",b,c,d,f,l,g=0;for(e=e.replace(/[^A-Za-z0-9\+\/\=]/g,"");g<e.length;)b=this._keyStr.indexOf(e.charAt(g++)),c=this._keyStr.indexOf(e.charAt(g++)),f=this._keyStr.indexOf(e.charAt(g++)),l=this._keyStr.indexOf(e.charAt(g++)),b=b<<2|c>>4,c=(c&15)<<4|f>>2,d=(f&3)<<6|l,a+=String.fromCharCode(b),64!==f&&(a+=String.fromCharCode(c)),64!==l&&(a+=String.fromCharCode(d));return a=Base64._utf8_decode(a)},_utf8_encode:function(e){e=e.replace(/\r\n/g,"\n");for(var a="",b=0;b<e.length;b++){var c=
e.charCodeAt(b);128>c?a+=String.fromCharCode(c):(127<c&&2048>c?a+=String.fromCharCode(c>>6|192):(a+=String.fromCharCode(c>>12|224),a+=String.fromCharCode(c>>6&63|128)),a+=String.fromCharCode(c&63|128))}return a},_utf8_decode:function(e){for(var a="",b=0,c,d,f=0;b<e.length;)c=e.charCodeAt(b),128>c?(a+=String.fromCharCode(c),b++):191<c&&224>c?(d=e.charCodeAt(b+1),a+=String.fromCharCode((c&31)<<6|d&63),b+=2):(d=e.charCodeAt(b+1),f=e.charCodeAt(b+2),a+=String.fromCharCode((c&15)<<12|(d&63)<<6|f&63),b+=
3);return a}},CWUtils=new CWUtilsClass;
