var __extends=this&&this.__extends||function(){var e=function(c,a){e=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,g){a.__proto__=g}||function(a,g){for(var c in g)g.hasOwnProperty(c)&&(a[c]=g[c])};return e(c,a)};return function(c,a){function b(){this.constructor=c}e(c,a);c.prototype=null===a?Object.create(a):(b.prototype=a.prototype,new b)}}(),CWPDFReaderPublisher=function(e){function c(){var a=e.call(this)||this;a.recordsOnPage=[];a.extractReferences=!0;return a}__extends(c,e);
c.prototype.init=function(){var a=this;if(CWUtils.isIframe)try{PDFJS=window["pdfjs-dist/build/pdf"];PDFJS.GlobalWorkerOptions.workerSrc=CWPDFReaderConfig.staticDomainURL+"/js/webpdf/lib/pdf.worker.js?v="+(CWPDFReaderConfig.version||1);-1<navigator.userAgent.toLowerCase().indexOf("firefox")&&PDFJS&&(PDFJS.disableWorker=!0);var b=CwZ("#cw-pdfReaderConfig").html();void 0!==b&&""!==CwZ.trim(b)&&(CWPDFReaderConfig=b=JSON.parse(b));CWUtils.log("LOADING FRAME...:"+CWPDFReaderConfig.cwURL);this.CWIFrameManager=
new IframeManager;this.CWIFrameManager.setListener(function(b){return a.onMessage(b)});this.CWIFrameManager.tell("iframe-loaded",{view:"mainExt",source:"pdfFrame"});this.initFileLoad(window.parent.CWPDFReader_Publisher.getInstance().urlToOpen)}catch(c){CWUtils.log(c)}};c.prototype.appendDivToHTML=function(a,b,c){CwZ(".referenceHTMLTopDiv").remove();var e=b;b-=155;c+=25;var f=a.title,d=48-f.length;0<d&&(b+=2*d);var d=a.doi,h,k;d?h="http://dx.doi.org/"+CwZ.trim(d):k=f?"https://scholar.google.com.pk/scholar?hl=en&q="+
encodeURIComponent(CwZ.trim(f)):"";a.author&&(f=a.author.replace(/\s{2}/," ").replace(/[;|(|)|"|:|<|>|\[|\]]/g,"").replace(/\s*(\beds\b\.?|\bet al\b\.?|ed\.?)\s*/i,"").replace(" and "," ").match(/\w+(,\s(\w{1}\.?)+)?/g).join('" "'),encodeURIComponent('"'+CwZ.trim(f)+'"'));""===a.title&&(a.title=a.refText);var f=CwZ(window).scrollTop()+CwZ(window.top).height(),l="posTop";c+100>f&&(l="posDown");d=0;0>b&&(d=b,b=0);a.posClass=l;a.scholarURL=k;a.url=h;a.x=Math.floor(b);a.y=Math.floor(c);a.emPos=e-b;a=
CWHtmlStructure.getReferenceTip(a,!0);CwZ("#cw-pdfDocument").prepend(a);a=CwZ(".referenceHTMLTopDiv").height();window.isCwMobile.any()&&CwZ(".referenceHTMLTopDiv").addClass("mobile");b=Math.floor(CwZ(".referenceHTMLTopDiv").css("top").replace("px",""));0!==d&&(d=CwZ(".referenceHTMLTopDiv").width()/2+d,CwZ(".referenceHTMLTopDiv").find("em").css("left",d+"px"));c+a+40>f&&(CwZ(".referenceHTMLTopDiv").css("top",b-a-60),CwZ(".referenceHTMLTopDiv").removeClass("posTop").addClass("posDown"));CwZ(".referenceHTMLTopDiv").show();
CwZ(".referenceHTMLTopDiv .refLinkContainer").off("click").on("click",function(){CWEventTracker.pushEvent("viewArticleFromPopup")})};c.prototype.onMessage=function(a){CWUtils.log("pdfreader_publisher CWPDFReader.onMessage:"+a.message);switch(a.message){case "getFileBlob":this.initFileLoad(a.data);break;case "referenceID":try{var b=a.data.referenceId,c=void 0;try{b=b.trim(),c=/^\+?(0|[1-9]\d*)$/.test(b)}catch(e){}c?(CWUtils.log(a.data.authorFound+" : "+b),b<=this.recordsOnPage.length?this.appendDivToHTML(this.recordsOnPage[b-
1],a.data.annotLinkX,a.data.annotLinkY):CWPageManager.navigateTo(a.data.dest)):a.data.dest?CWPageManager.navigateTo(a.data.dest):CWPageManager.navigateTo(b)}catch(f){CWPageManager.navigateTo(a.data.dest)}break;case "navigateToReference":CWPageManager.navigateTo(a.data.dest);break;case "recordsOnPage":this.recordsOnPage=a.data.records;this.loadReferences(this.recordsOnPage);this.generateReaderYearJSON(this.recordsOnPage);this.extractReferences=!0;break;case "setPublicationId":this.pubIdUrl=a.data.gotoLibUrl;
break;case "checkLoginResponse":a.data.isLogin?CwZ("#cw-pdfReaderAdd").hasClass("button-disabled")?(this.openViewInLibraryWindow(""===this.pubIdUrl?CWPDFReaderConfig.cwURL+"/library":CWPDFReaderConfig.cwURL+"/library?reader=1&pubId="+this.pubIdUrl),CWEventTracker.pushEvent("viewInLibraryFromReader")):(CwZ(".cw-tip-save-library").hide(),this.showWaitingMsg(),this.CWIFrameManager.tell("addtolib",{message:"Add to Lib",showSignIn:!1,view:"mainExt"}),this.closeViewInLibraryWindow()):(CwZ(".cw-atl-tip .cw-atl-content").show(),
CwZ("#cw-pdfReaderAdd").find("span").text("Add to Library"),CwZ("#cw-pdfReaderAdd").find("svg").find("use").attr("xlink:href","#icon-cloud").end().attr("class","icon-cloud"),CwZ(".listLinkContainer").find("a.addToLib").text("Add to Library"),this.closeViewInLibraryWindow());break;case "authArr":CWDataHolder.authorsArr=a.data.authors;break;case "checkDownloadResponse":a=a.data.isLogin;CWDataHolder.hasSuppMaterial||!a?CwZ(".cw-download-content").show():CwZ('.cw-btn[data-action="downloadPdf"]').trigger("click");
break;case "sendJSONToReader":this.jsonProfileData=a.data.jsonData;break;case "logoutCallback":this.CWIFrameManager.tell("showLogoutBox",{message:"showLogoutBox",view:"mainExt"});this.showAddMode();CwZ(".cw-user").hide();CwZ("#cw-gotoLibrary").hide();CwZ("#sepGoToLib").hide();this.hideWaitingMsg();this.CWIFrameManager.tell("updateLogin",{message:"updateLog",view:"mainExt"});break;case "showLogoutBox":CwZ(".cw-user").hide();CwZ("#cw-gotoLibrary").hide();CwZ("#CWLogoutDialog").show();break;case "updateUser":CWPDFReader.updateUser(a.data);
break;case "showServerDown":CwZ("#CWServerNotFound").show();break;case "hideWaitingMsg":this.hideWaitingMsg();break;case "hideSyncingDisplay":CwZ("#cw-pdfReaderAdd").show();CwZ("#cw-pdfReaderSync").hide();CwZ("#cw-gotoLibrary").hide();CwZ("#sepGoToLib").hide();CwZ(".cw-process").hide();break;case "showLoginPrompt":CwZ(".loginPromt").show();CwZ(".loginPromt .closeBtn").off("click").on("click",function(){CwZ(".loginPromt").hide()});CwZ(".loginPromt #signupBox").off("click").on("click",function(){this.showWaitingMsg();
CwZ(".loginPromt").hide();this.tell("addtolib",{message:"Add to Lib",showSignIn:!1,view:"mainExt"})});CwZ(".loginPromt #loginBox").off("click").on("click",function(){this.showWaitingMsg();CwZ(".loginPromt").hide();this.tell("addtolib",{message:"Add to Lib",showSignIn:!0,view:"mainExt"})});break;case "hideLoginPrompt":CwZ(".loginPromt").hide();break;case "url":this.pubOpened=a.data.pubSelected;break;case "setRelatedPubs":this.setRelatedPubs(a);break;case "initiateRelatedPubs":this.setRelatedPubs();
break;case "setLogin":CWDataHolder.isLogin=a.data.value;break;case "addRelatedPubResp":this.relatedAddToLib(void 0,a.data.data);break;case "citationHTML":CWCitationMaker.appendCitationHTML(a.data.citationHTML);break;case "cslJsonResponse":CWCitationMaker.bindCitControlEvents(a.data.cslJson);break;case "ajaxCallResp":this.ajaxCallback(a.data.data)}};c.prototype.initFileLoad=function(a){var b=CwZ(".cw-tabNavigator .cw-selected").data("tab");b&&(CwZ(".cw-tabContainer .cw-tabData").hide(),CwZ(".cw-tabContainer #"+
b).show());this.initDialogEvents();this.showDocumentLoader();CWUtils.log("in initFileLoad");CWUtils.log(a);CWPDFManager.openFile(a)};c.prototype.showDocumentLoader=function(){};return c}(CWPDFReaderClass),CWPDFReader=new CWPDFReaderPublisher;
