var SCROLLBAR_PADDING,parseQueryString,CSS_UNITS=96/72,CWPDFManagerClass=function(){function f(){this.loading=!1;this.destinationsPromise=this.pdf=null;this.pagesRefMap={};this.tsLoadingStart=0;this.viewMode="";this.documentInfo=this.metadata=null;this.viewModes={height:1,width:2,other:3}}f.prototype.openFile=function(a,b){CWPDFReader.initialize();CWUtils.log("in openFIle");CWUtils.log("openFileURL: "+a);this.loading=!0;this.tsLoadingStart=(new Date).getTime();var c=this,d=function(a){c.progress(a.loaded/
a.total)},e={url:a};try{PDFJS.openExternalLinksInNewWindow=!0,PDFJS.getDocument(e,null,null,d).then(function(a){CWPDFManager.pdf=a;c.loadPDF(a);c.loading=!1},function(b,d){var e="An error occurred while loading the PDF.";if(b&&(e="There was an error opening this document. Invalid or corrupted PDF file.",CWPDFReaderConfig.isDesktopMode())){var g={};g.msg=e;g.onOk=function(){window.parent.postMessage({message:"closepdf",data:CWPDFReader.commentsSyncPending,frameId:window.frameElement.id},"*")};CWPDFReaderDialog.show(g)}d&&
"MissingPDFException"===d.name&&(e="Missing PDF file.");CWPDFReaderConfig.isDesktopMode()||void 0!==CWPDFReader.errorLoadingFile&&CWPDFReader.errorLoadingFile(a);CWUtils.log(e);c.loading=!1})}catch(g){CWPDFReaderConfig.checkReaderMode("library")?PDFRaven.captureException(g.stack):CwZ(document).trigger("cwExcToSentry",g)}};f.prototype.loadPDF=function(a){var b=this;try{CWPDFReader.onRenderComplete(),CWPDFReaderConfig.isCoreMode()||CWPDFReaderConfig.isDesktopMode()||(CWEventTracker.pushEvent("viewpdf"),
CWPDFReader.CWIFrameManager.tell("hideSplashScr",{view:"mainExt"})),CWPageManager.init({pdf:a,containerId:"cw-pdfDocument",thumbContainerId:"cw-thumbView"}),CWPDFReader.initializeScrollContent(),a.getMetadata().then(function(a){var e=a.info;a=a.metadata;b.documentInfo=e;b.metadata=a;CWUtils.log("PDF "+b.pdf.fingerprint+" ["+e.PDFFormatVersion+" "+(e.Producer||"-").trim()+" / "+(e.Creator||"-").trim()+"] (PDF.js: "+(PDFJS.version||"-")+(PDFJS.disableWebGL?"":" [WebGL]")+")");e.IsAcroFormPresent&&(console.warn("Warning: AcroForm/XFA is not supported"),
self.fallback(PDFJS.UNSUPPORTED_FEATURES.forms))})}catch(c){CWPDFReaderConfig.checkReaderMode("library")?PDFRaven.captureException(c.stack):CwZ(document).trigger("cwExcToSentry",c)}};f.prototype.loadOutline=function(){CWPageManager.bAllPagesLoaded?CWPDFManager.pdf.getOutline().then(function(a){this.outline=new DocumentOutlineView(a)}):setTimeout(function(){CWPDFManager.loadOutline()},2E3)};f.prototype.loadPage=function(a){try{CWPDFManager.pdf.getPage(a.getPageNumber()).then(function(b){try{1===a.getPageNumber()&&
(new CWPDFDataImporter(b)).process()}catch(d){CWUtils.log(d)}a.initPage(b)})}catch(b){CWPDFReaderConfig.checkReaderMode("library")?PDFRaven.captureException(b.stack):CwZ(document).trigger("cwExcToSentry",b)}};f.prototype.progress=function(a){CwZ("#cw-loader .cw-progress").addClass("cw-indefinite");isNaN(a)?CwZ("#cw-loader .cw-bar").width("100%"):CwZ("#cw-loader .cw-bar").width(Math.floor(100*a)+"%")};f.prototype.searchText=function(a,b,c){var d=document.createEvent("CustomEvent");d.initCustomEvent("find"+
b,!0,!0,{query:a,caseSensitive:!1,highlightAll:!0,findPrevious:c});return window.dispatchEvent(d)};return f}(),CWPDFManager=new CWPDFManagerClass,CWPageManagerClass=function(){function f(){this.currentPage=this.totalPages=0;this.zoomLevel=1;this.scale=100;this.thumbZoomLevel=.3;this.pageToRenderInAdvance=window.isCwMobile.any()?3:5;this.thumbContainerId=this.containerId=null;this.bAllPagesLoaded=!1;this.pages=[];this.pgHeights=[];this.visiblePages=isMobileDevice()?[0,1]:[0,1,2,3];this.renderedPages=
[];this.scrollPosition={x:0,y:0};this.fitHeight=this.fitWidth=this.checkedFirstPage=!1;this.zoomLevelValue=window.isCwMobile.any()?mobileConfig.ZOOM_LEVEL:250;this.startScroll=0}f.prototype.init=function(a){this.totalPages=a.pdf._pdfInfo.numPages;this.currentPage=1;this.containerId=a.containerId;this.thumbContainerId=a.thumbContainerId;a=window.isCwMobile.any()?mobileConfig.ZOOM_LEVEL:250;this.setZoomLevelOnStart(a)};f.prototype.getZoomLevel=function(){return CWPageManager.zoomLevel};f.prototype.checkAllPagesLoaded=
function(){if(CWPageManager.bAllPagesLoaded)return CWPageManager.bAllPagesLoaded;if(this.pages.length<this.totalPages)return!1;for(var a=0,a=0;a<this.pages.length;a++)if(!this.pages[a].bLoaded)return!1;if(a===this.pages.length)return CWPageManager.bAllPagesLoaded=!0};f.prototype.loadPages=function(){try{for(var a=this.containerId,b=1;b<=this.totalPages;b++)if(!(0<CwZ("#cw-page-"+b).length)){var c=new CWPage({containerId:a,pageNumber:b});this.pages[b-1]=c;CWPDFManager.loadPage(c)}CWAnnotate.init();
PDFFindController.initialize()}catch(d){CWPDFReaderConfig.checkReaderMode("library")?PDFRaven.captureException(d.stack):CwZ(document).trigger("cwExcToSentry",d)}};f.prototype.onPageLoadComplete=function(){CWPageManager.checkedFirstPage||(CWPageManager.checkedFirstPage=!0,CWPDFReaderConfig.isDesktopMode()&&(CWPDFReader.previousState=CWApiHandler.getState(),CWPDFReader.goToPreviousState(CWPDFReader.previousState)));CWPageManager.checkAllPagesLoaded()&&(CWPageManager.updateAllPageSize(),CWPageManager.renderPages(),
CWCommentManager.commentSideBar.showInfoTip())};f.prototype.updateAllPageSize=function(){var a=CWPageManager.scrollPosition.y,b=CwZ("body")[0].scrollHeight,c=a/b;CWPageManager.pages.map(function(a){a.updateSize(!0);a.pdfPage.pageNumber===CWPageManager.totalPages&&(a=CwZ("body")[0].scrollHeight,CWUtils.moveScrollbarTo("body",c*a,!0),setTimeout(function(){CwZ(".cw-page").find("canvas").css("opacity","1");CwZ(".cw-page").find("section").css("opacity","1");CwZ(".cw-page").find(".cw-annotationCanvas").css("opacity",
"1")},400))})};f.prototype.renderPages=function(a){void 0===a&&(a=!0);var b=CWPageManager.visiblePages,c=CWPageManager.renderedPages;if(0!==CWPageManager.pages.length){CWPageManager.renderedPages=[];for(var d=[],e=0;e<b.length;e++){for(var g=b[e],f=!1,m=0;m<c.length;m++)if(g===c[m]){f=!0;CWPageManager.renderedPages.push(c[m]);break}f||d.push(b[e])}for(b=0;b<d.length;b++)(e=CWPageManager.pages[d[b]])&&e.bLoaded&&(e.renderPage(a),CWPageManager.renderedPages.push(d[b]));for(b=0;b<c.length;b++){e=CWPageManager.pages[c[b]];
f=!1;for(m=0;m<CWPageManager.renderedPages.length;m++)if(c[b]===CWPageManager.renderedPages[m]){f=!0;break}f||e.prune()}}};f.prototype.updateVisiblePages=function(a){a=CWPageManager.visiblePages?CWPageManager.visiblePages:[];CWPageManager.visiblePages=[];if(0===this.pgHeights.length)CWPageManager.visiblePages.push(0);else{for(var b=0,c=0,d=-1,e=-1,g=CwZ("body"),c=document.body.clientHeight,g=g.scrollTop(),f=g+c,m=window.isCwMobile.any()?mobileConfig.SCALE:CWPageManager.scale/100,n=!1,k=0;k<this.pgHeights.length;k++){c=
document.getElementById("cw-page-"+(k+1)).offsetTop+document.getElementById("cw-page-"+(k+1)).offsetHeight;c/=m;if(b<=f&&g<=c)-1===d&&(d=k),e=k,n=!0;else if(n)break;b=c}e===this.pgHeights.length&&0<this.pgHeights.length&&(e=this.pgHeights.length-1);b=(this.pageToRenderInAdvance-1)/2;for(d-=b;d<=e+b;d++)0<=d&&d<this.pgHeights.length&&CWPageManager.visiblePages.push(d)}return CWPageManager.visiblePages.toString()!==a.toString()};f.prototype.scalePage=function(a,b){var c=100,d=1,e=!1;a&&(c=CWPageManager.scale);
d=c*CSS_UNITS/100;d!==CWPageManager.zoomLevel&&(e=!0);CWPageManager.scale=100;CWUtils.log("newZoomLevel:"+c);window.isCwMobile.any()||CwZ(".cw-pageContent").css("zoom",CWPageManager.scale+"%");e&&(CWPageManager.zoomLevel=d,CWPageManager.renderedPages=[],CwZ(".cw-page").find("canvas").css("opacity","0"),CwZ(".cw-page").find("section").css("opacity","0"),CwZ(".cw-page").find(".cw-annotationCanvas").css("opacity","0"),CWPageManager.updateAllPageSize(),CWPageManager.renderPages(!1));try{var g=window.getSelection?
window.getSelection():document.selection;g&&(g.removeAllRanges?g.removeAllRanges():g.empty&&g.empty())}catch(f){CWUtils.log(f)}};f.prototype.setWidthFitScale=function(){null!==CWPDFManager.pdf&&CWPDFManager.pdf.getPage(CWPageManager.currentPage).then(function(a){a=a.getViewport(1).width;a=(document.body.clientWidth-50)/a*2;window.isCwMobile.any()&&(a*=mobileConfig.SCALE);a/=CSS_UNITS;CWPageManager.scale=100*a;CWPageManager.zoomLevelValue=CWPageManager.scale;a=CwZ("body");a={current:{y:a.scrollTop(),
x:a.scrollLeft()}};void 0!==a&&(CWPageManager.scrollPosition=a.current);CWPageManager.scalePage(!0)})};f.prototype.setZoomLevelOnStart=function(a){var b=a*CSS_UNITS/100;null!==CWPDFManager.pdf&&CWPDFManager.pdf.getPage(CWPageManager.currentPage).then(function(a){CWPageManager.zoomLevel=b;CWPageManager.loadPages()})};f.prototype.setHeightFitScale=function(a){null!==CWPDFManager.pdf&&CWPDFManager.pdf.getPage(CWPageManager.currentPage).then(function(b){b=b.getViewport(1).height;b=document.body.clientHeight/
b*2;window.isCwMobile.any()&&(b*=mobileConfig.SCALE);b/=CSS_UNITS;if(a){var c=CwZ("body"),c={current:{y:c.scrollTop(),x:c.scrollLeft()}};void 0!==c&&(CWPageManager.scrollPosition=c.current);CWPageManager.scale=100*b;CWPageManager.zoomLevelValue=CWPageManager.scale;CWPageManager.scalePage(!0)}})};f.prototype.nextPage=function(){if(CWPageManager.currentPage<CWPageManager.totalPages){CWPageManager.currentPage++;for(var a=CWPageManager.scale/100,b=CwZ("#cw-page-"+CWPageManager.currentPage).height()*a,
c=0,d=0,e=1;e<=CWPageManager.currentPage-1;e++)c+=b,d+=60;CWUtils.moveScrollbarTo(".cw-pageContent",c+d*a)}CWPageManager.currentPage>=CWPageManager.totalPages?CwZ('.cw-paging .cw-btn[data-action*="nextPage"]').addClass("disable-btn"):0<=CWPageManager.currentPage&&CwZ('.cw-paging .cw-btn[data-action*="prevPage"]').removeClass("disable-btn")};f.prototype.prevPage=function(){if(1<CWPageManager.currentPage){CWPageManager.currentPage--;for(var a=CWPageManager.scale/100,b=CwZ("#cw-page-"+CWPageManager.currentPage).height()*
a,c=0,d=0,e=1;e<=CWPageManager.currentPage-1;e++)c+=b,d+=60;CWUtils.moveScrollbarTo(".cw-pageContent",c+d*a)}0>=CWPageManager.currentPage?CwZ('.cw-paging .cw-btn[data-action*="prevPage"]').addClass("disable-btn"):CWPageManager.currentPage<=CWPageManager.totalPages&&CwZ('.cw-paging .cw-btn[data-action*="nextPage"]').removeClass("disable-btn")};f.prototype.moveToPage=function(a,b,c,d){setTimeout(function(){var e=void 0===c?!0:!1,g=CWPageManager.scale/100,g=((window.isCwMobile.any()?CwZ("#cw-page-"+
a).height()/3:CwZ("#cw-page-"+a).height())+30)*g;CWUtils.log("newH :"+g);g=CwZ("#cw-page-"+a).offset().top+b;CWUtils.moveScrollbarTo("body",g,e,d);e||(e=CwZ(window),e={current:{y:e.scrollTop(),x:e.scrollLeft()}},CWPageManager.onPageScrollEnd(e))},400)};f.prototype.getActualZoom=function(a){return a?Math.round(CWPageManager.scale*CWPageManager.zoomLevel/CSS_UNITS):CWPageManager.scale*CWPageManager.getZoomLevel()/100};f.prototype.getScale=function(){return CWPageManager.scale/100};f.prototype.getPageByIdx=
function(a){return null!==this.pages[a]?this.pages[a]:null};f.prototype.onPageScrollEnd=function(a){var b=0;void 0!==a&&(CWPageManager.scrollPosition=a.current,b=a.current.y,b+=document.body.clientHeight/2);((b=CWPageManager.updateVisiblePages(b))&&CWPDFReaderConfig.readerMode===CWPDFReaderMode.Chrome||b&&"undefined"!==typeof a)&&CWPageManager.bAllPagesLoaded&&CWPageManager.renderPages();CWPageManager.currentPage>=CWPageManager.totalPages?(CwZ('.cw-paging .cw-btn[data-action*="nextPage"]').addClass("disable-btn"),
CwZ('.cw-paging .cw-btn[data-action*="prevPage"]').removeClass("disable-btn")):1>=CWPageManager.currentPage?(CwZ('.cw-paging .cw-btn[data-action*="prevPage"]').addClass("disable-btn"),CwZ('.cw-paging .cw-btn[data-action*="nextPage"]').removeClass("disable-btn")):(CwZ('.cw-paging .cw-btn[data-action*="nextPage"]').removeClass("disable-btn"),CwZ('.cw-paging .cw-btn[data-action*="prevPage"]').removeClass("disable-btn"));CWDataHolder.pageCounterTimer=setTimeout(function(){CwZ(".cw-page-counter input").is(":focus")||
CWDataHolder.isOnPageCounter||CwZ(".cw-page-counter").fadeOut()},CWDataHolder.pageCounterDelay);CWPDFReader.changeState()};f.prototype.handleScroll=function(a){if(a.is(document))a.off("scroll").on("scroll",function(){CWPDFReaderConfig.readerMode===CWPDFReaderMode.Publisher&&Tether.position();CWDataHolder.lastActivity.scroll=(new Date).getTime();CWDataHolder.pageCounterTimer&&clearTimeout(CWDataHolder.pageCounterTimer);CwZ(".cw-page-counter").fadeIn();CwZ(".referenceHTMLTopDiv").remove();CwZ(".cw-text-tip-edit").hide();
CWDataHolder.scrollEndTimer&&(clearTimeout(CWDataHolder.scrollEndTimer),delete CWDataHolder.scrollEndTimer);CWDataHolder.scrollEndTimer=setTimeout(function(){CWPageManager.onPageScrollEnd({current:{x:CwZ(a).scrollLeft(),y:CwZ(a).scrollTop()}})},200);CWPDFReader.pageCounterHandler();var b=-1*(CWDataHolder.oldScrollPos.y-CwZ(a).scrollTop());if(CwZ(".cw-text-tip:visible")){var c=parseInt(CwZ(".cw-text-tip").css("top"),10);CwZ(".cw-text-tip").css("top",c)}CwZ(".cw-text-tip-edit:visible")&&(c=parseInt(CwZ(".cw-text-tip-edit").css("top"),
10),CwZ(".cw-text-tip-edit").css("top",c-b));CWDataHolder.oldScrollPos={x:CwZ(a).scrollLeft(),y:CwZ(a).scrollTop()}})};f.prototype.navigateTo=function(a){var b=function(c){var d=c instanceof Object?CWPDFManager.pagesRefMap[c.num+" "+c.gen+" R"]:c+1;if(d){d>CWPageManager.pages.length&&(d=CWPageManager.pages.length);try{var e=CWPageManager.pages[d-1],g=0,f=0,m=window.isCwMobile.any()?mobileConfig.SCALE:CWPageManager.scale,n=e.pHeight/(m/100)/CSS_UNITS;switch(a[1].name){case "XYZ":g=a[2];f=a[3];g=null!==
g?g:0;f=null!==f?f:n;break;case "Fit":case "FitB":break;case "FitH":case "FitBH":f=a[2];break;case "FitV":case "FitBV":g=a[2];break;case "FitR":g=a[2];f=a[3];break;default:return}var k=CWPageManager.pages[0].pdfPage.getViewport(CWPageManager.getZoomLevel()).transform;CWPageManager.moveToPage(d,g*k[1]+f*k[3]+k[5])}catch(l){CWPageManager.moveToPage(d,10)}}else CWPDFManager.pdf.getPageIndex(c).then(function(a){CWPDFManager.pagesRefMap[c.num+" "+c.gen+" R"]=a+1;b(c)})};("string"===typeof a?CWPDFManager.pdf.getDestinations(a):
Promise.resolve(a)).then(function(c){var d=a;a=c;for(var e in c)e===d&&(a=c[e]);a instanceof Array&&b(a[0])})};return f}(),CWPageManager=new CWPageManagerClass,CWPage=function(){function f(a){this.svg=this.textLayer=this.jqTextLayerDiv=this.htmlTextLayerDiv=this.textLayerDiv=this.jqAnnotationCanvas=this.htmlAnnotationCanvas=this.annotationCanvas=this.jqPDFCanvas=this.htmlPDFCanvas=this.pdfCanvas=this.jqElement=this.element=this.jqContainer=this.container=this.pdfPage=null;this.pHeight=this.pWidth=
0;this.rendering=this.bLoaded=!1;this.pendingRenderContext=null;this.pageNumber=0;if(a.containerId)this.jqContainer=CwZ("#"+a.containerId+" .cw-pageContent"),this.container=this.jqContainer.get(0);else throw"Page: Page container is not defined";if(a.pageNumber)this.pageNumber=a.pageNumber;else throw"Page: Page number is not defined";a=this.pageNumber;this.htmlPDFCanvas='<canvas class="cw-pdfCanvas" style=""></canvas>';this.htmlTextLayerDiv='<div class="cw-textLayer" style=""></div>';this.htmlAnnotationCanvas=
'<div class="cw-annotationCanvas" style=""></div>';this.jqElement=CwZ('<div id="cw-page-'+a+'" data-page="'+a+'" class="cw-page" style=""></div>');this.jqContainer.append(this.jqElement);this.element=this.jqElement.get(0)}f.prototype.getPageNumber=function(){return this.pageNumber};f.prototype.getTextContent=function(){return this.pdfPage.getTextContent()};f.prototype.clearPage=function(){this.pdfCanvas&&this.pdfCanvas.getContext("2d").clearRect(0,0,this.pdfCanvas.width,this.pdfCanvas.height)};f.prototype.prune=
function(){this.jqPDFCanvas&&(this.pdfCanvas.getContext("2d").clearRect(0,0,this.pdfCanvas.width,this.pdfCanvas.height),this.jqPDFCanvas.remove(),delete this.jqPDFCanvas,delete this.pdfCanvas,this.pdfCanvas=this.jqPDFCanvas=null);this.jqTextLayerDiv&&(this.jqTextLayerDiv.remove(),delete this.jqTextLayerDiv,delete this.textLayerDiv,delete this.textLayer,this.textLayer=this.textLayerDiv=this.jqTextLayerDiv=null);this.jqAnnotationCanvas&&(this.jqAnnotationCanvas.remove(),delete this.jqAnnotationCanvas,
delete this.annotationCanvas,this.annotationCanvas=this.jqAnnotationCanvas=null);if(this.pdfPage&&this.pdfPage.pageNumber){var a=CwZ("#cw-page-"+this.pdfPage.pageNumber);CwZ(a).find("section").remove()}};f.prototype.initPage=function(a){CWPDFManager.pagesRefMap[a.ref.num+" "+a.ref.gen+" R"]=this.getPageNumber();this.pdfPage=a;a=a.getViewport(CWPageManager.getZoomLevel());this.pWidth=a.width/CWPageManager.getZoomLevel();this.pHeight=a.height/CWPageManager.getZoomLevel();this.updateSize(!0);this.bLoaded=
!0;CWPageManager.onPageLoadComplete()};f.prototype.updateSize=function(a){var b=this.pdfPage.getViewport(CWPageManager.getZoomLevel()),c=Math.round(b.width/2),b=Math.round(b.height/2);CWPageManager.pgHeights[this.getPageNumber()-1]=b;this.jqElement[0].style.width=c+"px";this.jqElement[0].style.height=b+"px";this.pdfCanvas&&(this.pdfCanvas.style.width=c,this.pdfCanvas.style.height=b,this.pdfCanvas.width=2*c,this.pdfCanvas.height=2*b,a||this.jqPDFCanvas.hide());this.jqAnnotationCanvas&&(this.jqAnnotationCanvas[0].style.width=
c+"px",this.jqAnnotationCanvas[0].style.height=b+"px");this.jqTextLayerDiv&&(this.jqTextLayerDiv[0].style.width=c+"px",this.jqTextLayerDiv[0].style.height=b+"px");a||(this.clearPage(),this.jqTextLayerDiv&&this.jqTextLayerDiv.empty())};f.prototype.renderPage=function(a){try{var b=this,c=CwZ("#cw-page-"+b.pdfPage.pageNumber);CwZ(c).find("section").remove();0===this.jqContainer.find(this.jqElement).length&&this.jqContainer.append(this.jqElement);this.jqPDFCanvas=this.jqPDFCanvas?this.jqPDFCanvas:CwZ(this.htmlPDFCanvas);
0===this.jqElement.find(this.jqPDFCanvas).length&&(this.pdfCanvas=this.jqPDFCanvas.get(0),this.jqElement.append(this.jqPDFCanvas));this.jqTextLayerDiv=this.jqTextLayerDiv?this.jqTextLayerDiv:CwZ(this.htmlTextLayerDiv);0===this.jqElement.find(this.jqTextLayerDiv).length&&(this.textLayerDiv=this.jqTextLayerDiv.get(0),this.jqElement.append(this.jqTextLayerDiv));this.jqAnnotationCanvas=this.jqAnnotationCanvas?this.jqAnnotationCanvas:CwZ(this.htmlAnnotationCanvas);0===this.jqElement.find(this.jqAnnotationCanvas).length&&
(this.annotationCanvas=this.jqAnnotationCanvas.get(0),this.jqElement.append(this.jqAnnotationCanvas),this.svg=SVG(this.annotationCanvas),this.svg.viewbox({x:0,y:0,width:this.pWidth,height:this.pHeight}),CWAnnotate.setSVG(this),CWAnnotate.init(this));var d=this.pdfPage.getViewport(CWPageManager.getZoomLevel()),e=this.textLayerDiv;a&&this.updateSize(!1);this.jqPDFCanvas.show();var f=this.pdfCanvas.getContext("2d"),p={textLayerDiv:e,pageIndex:this.getPageNumber(),isViewerInPresentationMode:!1,viewport:d};
this.textLayer=e?new TextLayerBuilder(p):null;var m={canvasContext:f,viewport:d,textLayer:this.textLayer};if(b.rendering)CWUtils.log("Queueing rendering for page "+b.getPageNumber()),b.pendingRenderContext=m;else{var n=function(a){b.rendering=!0;CWUtils.log("Rendering page"+b.getPageNumber());b.pdfPage.render(a).promise.then(function(){var a=CwZ("#cw-page-"+b.pdfPage.pageNumber);CwZ(a).find("section").remove();b.rendering=!1;CWUtils.log("Rendering complete"+b.getPageNumber());b.pendingRenderContext?
(a=b.pendingRenderContext,b.pendingRenderContext=null,d=a.viewport,CWUtils.log("Triggering rendering again"),n(a)):k(b.pdfPage,d,b.pdfCanvas,a)},function(a){b.rendering=!1;CWUtils.log("Rendering complete"+b.getPageNumber());b.pendingRenderContext&&(a=b.pendingRenderContext,b.pendingRenderContext=null,CWUtils.log("Triggering rendering again"),n(a))})},k=function(a,b,e,c){return a.getAnnotations().then(function(e){b=b.clone({dontFlip:!0});for(var d=0;b.transform&&d<b.transform.length;d++)b.transform[d]/=
2;for(d=0;d<CWDataHolder.customAnnotLinks.length;d++){var f=CWDataHolder.customAnnotLinks[d];f.isAdded||1!==a.pageNumber||(e.push(f),f.isAdded=!0)}d=new PDFLinkService;d.setDocument(CWPDFManager.pdf);PDFJS.AnnotationLayer.render({viewport:b,div:c[0],page:a,annotations:e,linkService:d});CwZ("#cw-page-"+a.pageNumber).find(".linkAnnotation a").on("mouseover",function(a){window.event=a;CwZ(".cw-pageContent a").each(function(a,b){CwZ(b).attr("target","_blank")})});1===a.pageNumber&&CwZ('.linkAnnotation[data-annotation-id*="author-"]').each(function(){var a=
CwZ(this).attr("data-annotation-id"),b=a.split("-title-")[1],a=a.split("author-")[1].split("-title")[0];CwZ(this).removeClass("linkAnnotation").addClass("cw-authorLink").attr("auid",a).attr("au-name-pdf",b)})})};n(m)}if(this.textLayer&&!window.isCwMobile.any()){var l=this;this.pdfPage.getTextContent().then(function(a){publisher.readerOptions.authorProfile?(new CWAuthorLinker).process(a,l.getPageNumber()).done(function(a){l.textLayer.setTextContent(a)}):l.textLayer.setTextContent(a)})}}catch(h){CWPDFReaderConfig.checkReaderMode("library")?
PDFRaven.captureException(h.stack):CwZ(document).trigger("cwExcToSentry",h)}};return f}(),PDFLinkService=function(){function f(){this._pagesRefCache=this.pdfHistory=this.pdfViewer=this.pdfDocument=this.baseUrl=null}f.prototype={setDocument:function(a,b){this.baseUrl=b;this.pdfDocument=a;this._pagesRefCache=Object.create(null)},setViewer:function(a){this.pdfViewer=a},setHistory:function(a){this.pdfHistory=a},navigateTo:function(a){var b=window.event,c=function(a,b,d){CwZ(b).closest(".cw-page").attr("data-page");
a=CwZ(b).closest(".cw-page").find(".cw-textLayer").children();var c=CwZ(b)[0].getBoundingClientRect(),f=c.left,k=c.top,l=CwZ(b).offset().top,h=CwZ(b).offset().left,q=!1;CwZ.each(a,function(a){if(!q&&(a=this.getBoundingClientRect(),(f+5>a.left&&f+5<a.right||10>a.width&&Math.floor(f+1)>=Math.floor(a.left)&&Math.floor(f+1)<=Math.floor(a.right))&&k+6>a.top&&k+6<a.bottom)){q=!0;for(var b=CwZ(this).text().trim(),e=this.previousSibling,g=CwZ(this.nextSibling),v=g.text(),r=g[0].getBoundingClientRect(),t=
0;r.left+r.width<f+c.width+4&&4>t;)t++,b+=" "+v,g=CwZ(g)[0].nextSibling,v=CwZ(g).text(),r=CwZ(g)[0].getBoundingClientRect();g="";for(r=0;3>r&&null!=e;)/^(\d{4}[a-z]?)$/.test(CwZ(e).text())||(r++,g=" "+CwZ(e).text()+g),e=e.previousSibling;for(r=CwZ(this).text();CwZ(this).get(0).getBoundingClientRect().right>c.left&&""!==CwZ(this).text();)CwZ(this).text(CwZ(this).text().substr(0,CwZ(this).text().length-1));e=CwZ(this).text().length;CwZ(this).text(r);r=b.length;t="";t=17<r?b.substr(r-17,r):g+b;-1<t.indexOf("table")||
-1<t.indexOf("Table")||-1<t.indexOf("figure")||-1<t.indexOf("Figure")?CWPageManager.navigateTo(d):CWPDFReader.CWIFrameManager.tell("parseTargetLink",{message:"parseTargetLink",data:{linkIndex:e,linkRect:{left:c.left,width:c.width},divRect:{left:a.left,width:a.width},preTargetText:g,postTargetText:v,targetText:b,dest:d,annotLinkPosX:f,annotLinkPosY:k,itemsArr:referenceCollector.getTestReference(),appendPos:{left:h,top:l}},view:"mainExt"})}});q||CWPageManager.navigateTo(d)},d=function(b){var c=b instanceof
Object?CWPDFManager.pagesRefMap[b.num+" "+b.gen+" R"]:b+1;if(c){c>CWPageManager.pages.length&&(c=CWPageManager.pages.length);try{var f=CWPageManager.pages[c-1],m=0,n=0,k=0,l=0,h=void 0,q=void 0,u=f.pWidth/(CWPageManager.scale/100)/CSS_UNITS,x=f.pHeight/(CWPageManager.scale/100)/CSS_UNITS;switch(a[1].name){case "XYZ":m=a[2];n=a[3];m=null!==m?m:0;n=null!==n?n:x;break;case "Fit":case "FitB":break;case "FitH":case "FitBH":n=a[2];break;case "FitV":case "FitBV":m=a[2];k=u;l=x;break;case "FitR":var m=a[2],
n=a[3],k=a[4]-m,l=a[5]-n,y=this.container,h=(y.clientWidth-SCROLLBAR_PADDING)/k/CSS_UNITS,q=(y.clientHeight-SCROLLBAR_PADDING)/l/CSS_UNITS;Math.min(Math.abs(h),Math.abs(q));break;default:return}var w=CWPageManager.pages[0].pdfPage.getViewport(CWPageManager.getZoomLevel()).transform;CWPageManager.moveToPage(c,m*w[1]+n*w[3]+w[5])}catch(v){CWPageManager.moveToPage(c,10)}}else CWPDFManager.pdf.getPageIndex(b).then(function(a){CWPDFManager.pagesRefMap[b.num+" "+b.gen+" R"]=a+1;d(b)})};CWPDFReader.extractReferences&&
b?(c(b,b.target||b.srcElement,a),CWEventTracker.pushEvent("referenceClick")):a&&(b=void 0,b="string"===typeof a?this.pdfDocument.getDestination(a):Promise.resolve(a),b.then(function(b){a=b;b instanceof Array&&d(b[0])}))},getDestinationHash:function(a){if("string"===typeof a)return this.getAnchorUrl("#"+escape(a));if(a instanceof Array){var b=a[0];if(b=b instanceof Object?CWPDFManager.pagesRefMap[b.num+" "+b.gen+" R"]:b+1){var b=this.getAnchorUrl("#page="+b),c=a[1];if("object"===typeof c&&"name"in
c&&"XYZ"===c.name){var c=a[4]||this.currentScaleValue,d=parseFloat(c);d&&(c=100*d);b+="&zoom="+c;if(a[2]||a[3])b+=","+(a[2]||0)+","+(a[3]||0)}return b}}return this.getAnchorUrl("")},getAnchorUrl:function(a){return(this.baseUrl||"")+a},setHash:function(a){if(0<=a.indexOf("="))if(a=parseQueryString(a),"nameddest"in a)this.pdfHistory&&this.pdfHistory.updateNextHashParam(a.nameddest),this.navigateTo(a.nameddest);else{var b=void 0,c=void 0;"page"in a&&(b=a.page|0||1);if("zoom"in a){var d=a.zoom.split(","),
e=d[0],f=parseFloat(e);-1===e.indexOf("Fit")?c=[null,{name:"XYZ"},1<d.length?d[1]|0:null,2<d.length?d[2]|0:null,f?f/100:e]:"Fit"===e||"FitB"===e?c=[null,{name:e}]:"FitH"===e||"FitBH"===e||"FitV"===e||"FitBV"===e?c=[null,{name:e},1<d.length?d[1]|0:null]:"FitR"===e?5!==d.length?console.error("PDFLinkService_setHash: Not enough parameters for 'FitR'."):c=[null,{name:e},d[1]|0,d[2]|0,d[3]|0,d[4]|0]:console.error("PDFLinkService_setHash: '"+e+"' is not a valid zoom value.")}c?this.pdfViewer.scrollPageIntoView(b||
this.page,c):b&&(this.page=b);"pagemode"in a&&(b=document.createEvent("CustomEvent"),b.initCustomEvent("pagemode",!0,!0,{mode:a.pagemode}),this.pdfViewer.container.dispatchEvent(b))}else/^\d+$/.test(a)?this.page=a:(this.pdfHistory&&this.pdfHistory.updateNextHashParam(unescape(a)),this.navigateTo(unescape(a)))},executeNamedAction:function(a){switch(a){case "GoBack":this.pdfHistory&&this.pdfHistory.back();break;case "GoForward":this.pdfHistory&&this.pdfHistory.forward();break;case "NextPage":this.page++;
break;case "PrevPage":this.page--;break;case "LastPage":this.page=this.pagesCount;break;case "FirstPage":this.page=1}var b=document.createEvent("CustomEvent");b.initCustomEvent("namedaction",!0,!0,{action:a});this.pdfViewer.container.dispatchEvent(b)},cachePageRef:function(a,b){this._pagesRefCache[b.num+" "+b.gen+" R"]=a}};return f}();
function CWThumbnail(f){this.thumbCanvas=null;var a=0,b=null;this.getPageNumber=function(){return a};if(f.containerId)b=CwZ("#"+f.containerId+" .cw-tabContent");else throw"Thumbnail: Page container is not defined";if(f.pageNumber)a=f.pageNumber;else throw"Thumbnail: Page number is not defined";f=a;b.append('<div id="cw-thumb-'+f+'" data-page="'+f+'" class="cw-thumb"><a href="javascript:void(0);"><canvas class="cw-thumbCanvas"></canvas></a></div>');this.thumbCanvas=CwZ("#cw-thumb-"+f).find(".cw-thumbCanvas").get(0)}
CWThumbnail.prototype.clearPage=function(){var f=this.thumbCanvas;f.getContext("2d").clearRect(0,0,f.width,f.height)};
var DocumentOutlineView=function(f){function a(a,b){"string"===typeof b.dest&&(a.href="#"+escape(b.dest));a.onclick=function(a){CWPageManager.navigateTo(b.dest);return!1}}for(var b=document.getElementById("cw-outlineView");b.firstChild;)b.removeChild(b.firstChild);for(f=[{parent:b,items:f}];0<f.length;)for(var b=f.shift(),c=void 0,d=b.items.length,c=0;c<d;c++){var e=b.items[c],g=document.createElement("div");g.className="outlineItem";var p=document.createElement("a");a(p,e);p.textContent=e.title;
g.appendChild(p);0<e.items.length&&(p=document.createElement("div"),p.className="outlineItems",g.appendChild(p),f.push({parent:p,items:e.items}));b.parent.appendChild(g)}},CWAuthorLinker=function(){function f(a,c,d,e){var f=a.split(" ");a=f[f.length-1];f=f[0];-1<d.indexOf(a)&&(c.mergeData={lastIndex:d.indexOf(a)},-1<d.indexOf(f)?(c.mergeData.startIndex=d.indexOf(f),e.push(c)):-1<d.indexOf(f[0]+".")?(c.mergeData.startIndex=d.indexOf(f[0]+"."),e.push(c)):d.substr(0,d.indexOf(a)).indexOf(f[0])?(c.mergeData.startIndex=
d.substr(0,d.indexOf(a)).indexOf(f[0]),e.push(c)):delete c.mergeData);return c.mergeData?!0:!1}this.process=function(b,c){var d=CwZ.Deferred();0<CwZ("#cw-page-"+c+" .cw-authorLink").length&&CwZ("#cw-page-"+c).find(".cw-textLayer").html("");if(0<c)d.resolve(b);else if(0<Object.keys(CWDataHolder.authorsArr).length){for(var e=[],f=Object.keys(CWDataHolder.authorsArr),p=0;p<f.length;p++)e.push(CWDataHolder.authorsArr[f[p]]);d.resolve(a(b,e))}else CWDataHolder.getAuthorsArr().then(function(c){var e=[];
try{c.each(function(){e.push(this)})}catch(f){CWUtils.log(f)}d.resolve(a(b,e))},function(){d.resolve(b)});return d.promise()};var a=function(a,c){var d,e,g=a.items;if(c.length===CwZ(".cw-authorLink").length)return a;d=g[0].str;e=0;for(var p=1;p<g.length;p++){var m=g[p],n=g[p-1];if(0===c.length)break;if(m.transform[5]===n.transform[5])d=Math.floor(m.transform[4])===Math.floor(n.transform[4]+n.width)?d+m.str:d+(" "+m.str);else{n=c;d.replace(/\.|,/g,"").replace(/\s+/g," ").trim().toLowerCase();d=d.replace(/\s+/g,
" ").trim().toLowerCase();for(var k=[],l=0;l<n.length;l++){var h=n[l];"undefined"!==typeof h.mergeData&&delete h.mergeData;var q=!1;h.bestName&&(q=f(h.bestName.replace(/\*/g,"").toLowerCase().trim(),h,d,k));q||(q=f(h.fullName.replace(/\*/g,"").toLowerCase().trim(),h,d,k),h.bestName=h.fullName);q&&(n.splice(l,1),l=-1)}n=k;if(0<n.length){d=g;e={start:e,end:p};k=JSON.parse(JSON.stringify(d[e.start]));for(l=e.start+1;l<e.end;l++)h=d[l],q=d[l-1],h.height>q.height&&(k.height=h.height),h.transform[0]<q.transform[0]&&
(k.transform[0]=h.transform[0]),h.transform[3]<q.transform[3]&&(k.transform[3]=h.transform[3]),k.width+=h.width,k.str=Math.floor(h.transform[4])===Math.floor(q.transform[4]+q.width)?k.str+h.str:k.str+(" "+h.str);d.splice(e.start,e.end-e.start,k);d=e.start;e=e.end-e.start;p=p-e+1;e=g[d];d=e.str.replace(/\s+/g," ");for(k=0;k<n.length;k++){l=n[k];h=l.bestName;h=("undefined"!==typeof h?h:l.fullName).trim().replace(/\*/g,"").split(" ");q=h[h.length-1];h=void 0;l.mergeData&&(h=d.trim().substr(l.mergeData.startIndex,
l.mergeData.lastIndex+q.length-l.mergeData.startIndex));var q=e.width/e.str.length,u=e.transform[4]+e.str.indexOf(h)*q;CWDataHolder.customAnnotLinks.push({annotationFlags:0,subtype:"Link",rect:[u,e.transform[5]-5,u+(h.length+1)*q,e.transform[5]+e.height],color:[0,0,0],borderStyle:{width:0,style:1,dashArray:[3],horizontalCornerRadius:0,verticalCornerRadius:0},hasAppearance:!1,id:"author-"+l.id+"-title-"+h,auid:l.id,autitle:h,hasHtml:!0,annotationType:2,customClass:"cw-authorLink",url:CWPDFReaderConfig.cwURL+
"/auapi/public?x=1&authorId="+l.id})}e.hasAuthor=!0}e=p;d=m.str}}a.items=g;return a}};
