var CustomStyle=function(){function g(){}var q=["ms","Moz","Webkit","O"],e={};g.getProp=function(a,d){if(1===arguments.length&&"string"===typeof e[a])return e[a];d=d||document.documentElement;var c=d.style,b,f;if("string"===typeof c[a])return e[a]=a;f=a.charAt(0).toUpperCase()+a.slice(1);for(var m=0,h=q.length;m<h;m++)if(b=q[m]+f,"string"===typeof c[b])return e[a]=b;return e[a]="undefined"};g.setProp=function(a,d,c){a=this.getProp(a);"undefined"!==a&&(d.style[a]=c)};return g}(),TextLayerBuilder=function(g){var q=
document.createDocumentFragment();this.textLayerDiv=g.textLayerDiv;this.divContentDone=this.layoutDone=!1;this.pageIdx=g.pageIndex;this.matches=[];this.lastScrollSource=g.lastScrollSource;this.viewport=g.viewport;this.isViewerInPresentationMode=g.isViewerInPresentationMode;this.textDivs=[];"undefined"===typeof PDFFindController&&(window.PDFFindController=null);"undefined"===typeof this.lastScrollSource&&(this.lastScrollSource=null);this.renderLayer=function(){var e=this.textDivs,a=document.createElement("canvas").getContext("2d");
if(!(1E5<e.length)){for(var d=0,c=e.length;d<c;d++){var b=e[d];if(!("isWhitespace"in b.dataset)){a.font=b.style.fontSize+" "+b.style.fontFamily;var f=void 0,f="true"===b.dataset.edited?a.measureText(b.textContent.substring(0,b.textContent.length-1)).width:a.measureText(b.textContent).width;0<f&&(q.appendChild(b),f="scale("+parseFloat((b.dataset.canvasWidth/f).toFixed(3))/2+", 1)",f="rotate("+b.dataset.angle+"deg) "+f,CustomStyle.setProp("transform",b,f),CustomStyle.setProp("transformOrigin",b,"0% 0%"))}}this.textLayerDiv.appendChild(q);
this.renderingDone=!0;this.updateMatches()}};this.setupRenderLayoutTimer=function(){var e=this,a=null===this.lastScrollSource?0:this.lastScrollSource.lastScroll;200<Date.now()-a?this.renderLayer():(this.renderTimer&&clearTimeout(this.renderTimer),this.renderTimer=setTimeout(function(){e.setupRenderLayoutTimer()},200))};this.appendText=function(e,a){var d=a[e.fontName],c=document.createElement("div");this.textDivs.push(c);if(/\S/.test(e.str)){var b=PDFJS.Util.transform(this.viewport.transform,e.transform),
f=Math.atan2(b[1],b[0]);d.vertical&&(f+=Math.PI/2);var m=parseFloat(Math.sqrt(b[2]*b[2]+b[3]*b[3]).toString()).toFixed(2),h=parseFloat(m);d.ascent?h*=d.ascent:d.descent&&(h*=1+d.descent);c.style.position="absolute";0===f?(c.style.left=(parseFloat(b[4])/2).toFixed(2)+"px",c.style.top=(parseFloat((b[5]-.75*parseFloat(m)).toString())/2).toFixed(2)+"px"):(c.style.left=(parseFloat(b[4]+h*Math.sin(f))/2).toFixed(2)+"px",c.style.top=(parseFloat((b[5]-h*Math.cos(f)).toString())/2).toFixed(2)+"px");c.style.fontSize=
parseFloat(m)/2+"px";c.style.fontFamily=d.fontFamily;c.dataset.edited=e.edited;e.hasAuthor?c.innerHTML=e.str:c.textContent=e.str;c.dataset.fontName=e.fontName;c.dataset.angle=180/Math.PI*f;c.dataset.canvasWidth=d.vertical?e.height*this.viewport.scale:e.width*this.viewport.scale}else c.dataset.isWhitespace=!0};this.setTextContent=function(e){this.textContent=e;this.textLayerDiv.innerHTML="";for(var a=e.items,d=0;d<a.length;d++)" "!==a[d].str[a[d].str.length-1]&&d<a.length-1&&a[d].transform[5]!==a[d+
1].transform[5]&&(a[d].str+=" ",a[d].edited=!0),this.appendText(a[d],e.styles);this.divContentDone=!0;this.setupRenderLayoutTimer()};this.convertMatches=function(e){for(var a=0,d=0,c=this.textContent.items,b=c.length-1,f=null===PDFFindController?0:PDFFindController.state.query.length,m=[],h=0;h<e.length;h++){for(var g=e[h];a!==b&&g>=d+c[a].str.length;)d+=c[a].str.length,a++;a===c.length&&console.error("Could not find matching mapping");for(var n={begin:{divIdx:a,offset:g-d}},g=g+f;a!==b&&g>d+c[a].str.length;)d+=
c[a].str.length,a++;n.end={divIdx:a,offset:g-d};m.push(n)}return m};this.renderMatches=function(e){function a(){var a=window.navigator.userAgent,b=a.indexOf("MSIE ");if(0<b)return parseInt(a.substring(b+5,a.indexOf(".",b)),10);if(0<a.indexOf("Trident/"))return b=a.indexOf("rv:"),parseInt(a.substring(b+3,a.indexOf(".",b)),10);b=a.indexOf("Edge/");return 0<b?parseInt(a.substring(b+5,a.indexOf(".",b)),10):!1}function d(a){var b=q-1;CWPageManager.moveToPage(q,CwZ(a).position().top-b-120)}function c(a,
d){var c=a.divIdx;n[c].textContent="";b(c,0,a.offset,d)}function b(a,b,d,c){var e=n[a];a=g[a].str.substring(b,d);a=document.createTextNode(a);c?(b=document.createElement("span"),b.className=c,b.appendChild(a),e.appendChild(b)):e.appendChild(a)}if(0!==e.length){var f=a(),m="CSS"in window&&"supports"in window.CSS&&window.CSS.supports("mix-blend-mode","inherit"),h=!1;!1===f&&m||(h=!0);var g=this.textContent.items,n=this.textDivs,l=null,f=this.pageIdx,m=null===PDFFindController?!1:this.pageIdx===PDFFindController.selected.pageIdx+
1,q=PDFFindController.selected.pageIdx+1,v=PDFFindController.selected.matchIdx,t=v,w=t+1;if(PDFFindController.state.highlightAll)t=0,w=e.length;else if(!m)return;for(;t<w;t++){var p=e[t],k=p.begin,p=p.end,u=m&&t===v,r=u?" selected":"";this.findController&&this.findController.updateMatchPosition(f,t,n,k.divIdx);if(u&&(d(n[k.divIdx]),h?n[k.divIdx].className="highlight isIE":n[k.divIdx].className="highlight",h?n[p.divIdx].className="highlight isIE":n[p.divIdx].className="highlight",k.divIdx!==p.divIdx))for(u=
k.divIdx+1;u<p.divIdx;u++)h?n[u].className="highlight isIE":n[u].className="highlight";l&&k.divIdx===l.divIdx?b(l.divIdx,l.offset,k.offset):(null!==l&&b(l.divIdx,l.offset,void 0),c(k));if(k.divIdx===p.divIdx)h?b(k.divIdx,k.offset,p.offset,"highlight isIE"+r):b(k.divIdx,k.offset,p.offset,"highlight"+r);else{h?b(k.divIdx,k.offset,void 0,"highlight isIE begin"+r):b(k.divIdx,k.offset,void 0,"highlight begin"+r);l=k.divIdx+1;for(k=p.divIdx;l<k;l++)h?n[l].className="highlight isIE middle"+r:n[l].className=
"highlight middle"+r;h?c(p,"highlight isIE end"+r):c(p,"highlight end"+r)}l=p}l&&b(l.divIdx,l.offset,void 0)}};this.updateMatches=function(){if(this.renderingDone){for(var e=this.matches,a=this.textDivs,d=this.textContent.items,c=-1,b=0;b<e.length;b++){for(var f=e[b],c=Math.max(c,f.begin.divIdx);c<=f.end.divIdx;c++){var g=a[c];g.textContent=d[c].str;g.className=""}c=f.end.divIdx+1}null!==PDFFindController&&PDFFindController.active&&(this.matches=this.convertMatches(null===PDFFindController?[]:PDFFindController.pageMatches[this.pageIdx-
1]||[]),this.renderMatches(this.matches))}}};
