var CWCommentManagerClass=function(){function e(){this.annotationArr=[];this.deletedArr=[];this.commentSideBar=new CWSideBar;this.bCommentLoaded=!1;this.oldComments=this.selectedComments=null;this.annotationsOwner="";this.sidebarHtml={};this.commentsList={}}e.prototype.bUpdateCmt=function(b,d){if(parseInt(b.ts,10)>parseInt(d.ts,10)){if(b.Pos!==d.Pos){d.Pos=b.Pos;var a=d.Pos.split(","),c="";CwZ("#"+CWAnnotate.hashComment[d.uId]).attr("d");c+="m"+a[0]+","+a[1];c+="l0,-6l-3,0c-1.5,0 -3,-1.5 -3,-3l0,-5c0,-1.5 1.5,-3 3,-3l14,0c1.5,0 3,1.5 3,3l0,5c0,1.5 -1.5,3 -3,3l-7,0l-4,6z";
CwZ("#"+CWAnnotate.hashComment[d.uId]).attr("d",c)}return!0}return!1};e.prototype.bUpdateShp=function(b,d,a){var c="",m;for(m in b)if(1===m.length&&-1!=="ERHASF".indexOf(m)){c=m;break}var e="";for(m in d)if(1===m.length&&-1!=="ERHASF".indexOf(m)){e=m;break}if(parseInt(b.TS,10)>parseInt(d.TS,10)){if(b[c]&&d[e]&&b[c]!==d[e])for(d[e]=b[c],c=void 0,b=0;b<a.length;b++)if(a[b].ID===d.uId)if(d.R)c=d.R.split(","),a[b].points[1].x=c[0],a[b].points[1].y=c[1],CwZ("#"+CWAnnotate.hashComment[d.uId]).attr("x",
c[0]),CwZ("#"+CWAnnotate.hashComment[d.uId]).attr("y",c[1]);else if(d.E)c=d.E.split(","),a[b].points[0].x=c[0],a[b].points[0].y=c[1],m=parseInt(c[0],10)+parseInt(c[2],10)/2,c=parseInt(c[1],10)+parseInt(c[3],10)/2,CwZ("#"+CWAnnotate.hashComment[d.uId]).attr("cx",m),CwZ("#"+CWAnnotate.hashComment[d.uId]).attr("cy",c);else if(d.H)c=d.H.split(","),a[b].points[1].x=c[0],a[b].points[1].y=c[1],CwZ("#"+CWAnnotate.hashComment[d.uId]).attr("x",c[0]),CwZ("#"+CWAnnotate.hashComment[d.uId]).attr("y",c[1]);else if(d.A){c=
d.A.split(",");e=Math.atan2(c[3]-c[1],c[2]-c[0]);m=new CWPoint(c[2]-10*Math.cos(e-Math.PI/6),c[3]-10*Math.sin(e-Math.PI/6));var e=new CWPoint(c[2]-10*Math.cos(e+Math.PI/6),c[3]-10*Math.sin(e+Math.PI/6)),f="";CwZ("#"+CWAnnotate.hashComment[d.uId]).attr("d").split(",");f="M"+c[0]+","+c[1];f+="L"+c[2]+","+c[3];f+="M"+c[2]+","+c[3];f+="L"+m.x+","+m.y;f+="M"+c[2]+","+c[3];f+="L"+e.x+","+e.y;CwZ("#"+CWAnnotate.hashComment[d.uId]).attr("d",f)}else d.S&&(c=d.S.split(","),a[b].points[0].x=c[0],a[b].points[0].y=
c[1],a[b].points[1].x=c[2],a[b].points[1].y=c[3],CwZ("#"+CWAnnotate.hashComment[d.uId]).attr("x1",c[0]),CwZ("#"+CWAnnotate.hashComment[d.uId]).attr("y1",c[1]),CwZ("#"+CWAnnotate.hashComment[d.uId]).attr("x2",c[2]),CwZ("#"+CWAnnotate.hashComment[d.uId]).attr("y2",c[3]));return!0}return!1};e.prototype.mergeComments=function(b,d){if(""!==b){var a="",c=[],e=[];"undefined"!==typeof d&&d&&d.decodedObj?("undefined"!==typeof d.decodedObj.comments&&d.decodedObj.comments&&(c=d.decodedObj.comments),"undefined"!==
typeof d.decodedObj.deleted&&d.decodedObj.deleted&&(e=d.decodedObj.deleted)):(c=CWCommentManager.annotationArr,e=CWCommentManager.deletedArr);if(0<c.length||0<e.length)a=CWCodec.encode(c,e);if(""===a)a=b;else{e="";try{e=CwZ.parseJSON(b)}catch(g){try{var f=CWUtils.decompress(b),e=CwZ.parseJSON(f)}catch(q){q.stack+=" data:"+b,CWPDFReaderConfig.isCoreMode()||CWPDFReaderConfig.isDesktopMode()?PDFRaven.captureException(q.stack):CwZ(document).trigger("cwExcToSentry",q)}}var f={},r={},p={},h=void 0,a=a.split("\n").join(" ");
try{h=CwZ.parseJSON(a)}catch(t){t.stack+=" data:"+a,CWPDFReaderConfig.isCoreMode()||CWPDFReaderConfig.isDesktopMode()?PDFRaven.captureException(t.stack):CwZ(document).trigger("cwExcToSentry",t)}for(var k=h.List.MemberData[0].data.Comments,l=h.List.MemberData[0].data.Graphics,n=h.List.MemberData[0].data.Deleted?h.List.MemberData[0].data.Deleted:[],a=a=0;a<n.length;a++)p[n[a]]=n[a];n=void 0;try{n=e.List.MemberData[0].data.Deleted?e.List.MemberData[0].data.Deleted:[]}catch(w){n=[]}for(a=0;a<n.length;a++)p[n[a]]=
n[a];for(a=0;a<k.length;a++)p[k[a].uId]||(f[k[a].uId]=k[a]);for(a=0;a<l.length;a++)p[l[a].uId]||(r[l[a].uId]=l[a]);k=[];l=[];try{k=e.List.MemberData[0].data.Comments,l=e.List.MemberData[0].data.Graphics}catch(x){}for(a=0;a<k.length;a++)f[k[a].uId]?this.bUpdateCmt(k[a],f[k[a].uId])&&(f[k[a].uId].Cmnt=k[a].Cmnt):p[k[a].uId]||(f[k[a].uId]=k[a]);for(a=0;a<l.length;a++)r[l[a].uId]?this.bUpdateShp(l[a],r[l[a].uId],c)&&(r[l[a].uId].Cmt=l[a].Cmt):p[l[a].uId]||(r[l[a].uId]=l[a]);var k=[],u;for(u in f)k.push(f[u]);
h.List.MemberData[0].data.Comments=k;l=[];for(u in r)l.push(r[u]);h.List.MemberData[0].data.Graphics=l;var n=[],v;for(v in p)n.push(p[v]);h.List.MemberData[0].data.Deleted=n;a=JSON.stringify(h)}return a}return""};e.prototype.addUserToDD=function(b){0<CwZ(".cw-annotatorsDropDown").find('[data-id="'+b.uId+'"]').length||(b=CWHtmlStructure.getUserToDD(b.uId,b.uName||b.email),CwZ(".cw-annotatorsDropDown").append(b))};e.prototype.initDDFunc=function(){CwZ(".cw-annotatorsDropDown").off("change").on("change",
function(){var b=CwZ(".cw-annotatorsDropDown").val();CWCommentManager.annotationsOwner=CwZ(this).text();CWCommentManager.setSelectedComments(b)})};e.prototype.loadComments=function(b,d){try{CWCommentManager.bCommentLoaded=!0;var a="",c={};CWCommentManager.oldComments=CWCommentManager.selectedComments;if(CWPDFReaderConfig.isCoreMode()||CWPDFReaderConfig.isDesktopMode()){!b||CWCommentManager.selectedComments&&CWCommentManager.selectedComments.uId!==b.uId||(a=b.commentsString,CWCommentManager.selectedComments=
b,CWDataCenter.isReadOnly=!CWCommentManager.selectedComments.isCurrentUser);if(d){for(var e in d){var g=d[e];CWCommentManager.bCommentLoaded&&g.isCurrentUser&&(g.commentsString=CWCommentManager.mergeComments(g.commentsString,CWCommentManager.commentsList[e]));g.decodedObj=CWCodec.decode(g.commentsString);CWCommentManager.commentsList[e]=g;CWCommentManager.selectedComments&&(CWCommentManager.selectedComments.isDummy&&g.isCurrentUser||CWCommentManager.selectedComments.uId===g.uId)&&(b=CWCommentManager.selectedComments=
g,a=b.commentsString);CWCommentManager.addUserToDD(g)}CWCommentManager.initDDFunc();CwZ(".cw-annotatorsDropDown").val(CWCommentManager.selectedComments.uId);CWCommentManager.annotationArr=CWCommentManager.selectedComments.decodedObj.comments;CWCommentManager.deletedArr=CWCommentManager.selectedComments.decodedObj.deleted}else{if(CWCommentManager.bCommentLoaded){var f=CWCommentManager.mergeComments(b.commentsString);b.commentsString=f}b.decodedObj=CWCodec.decode(b.commentsString)}c=b.decodedObj;0<
c.comments.length&&(CWCommentManager.annotationArr=c.comments);CWCommentManager.deletedArr=c.deleted}else a=b,CWCommentManager.bCommentLoaded&&(a=f=CWCommentManager.mergeComments(a)),a&&(c=CWCodec.decode(a),0<c.comments.length&&(CWCommentManager.annotationArr=c.comments),this.deletedArr=c.deleted);""!==a&&null!==a&&void 0!==a&&(CWCommentManager.bCommentLoaded&&a===b&&CWCommentManager.mergeComments(a),CWCommentManager.updateList())}catch(q){CWPDFReaderConfig.isCoreMode()||CWPDFReaderConfig.isDesktopMode()?
PDFRaven.captureException(q.stack):CwZ(document).trigger("cwExcToSentry",q)}};e.prototype.getCommentsString=function(){if(CWPDFReaderConfig.checkReaderMode("drive")){var b=null,d;for(d in CWCommentManager.commentsList){var a=CWCommentManager.commentsList[d];if(a.isCurrentUser){b=CWCodec.encode(a.decodedObj.comments,a.decodedObj.deleted);break}}return b}return CWCodec.encode(CWCommentManager.annotationArr,CWCommentManager.deletedArr)};e.prototype.setSelectedComments=function(b,d){var a=null,a=b?CWCommentManager.commentsList[b]:
d;a.isCurrentUser?(CwZ("body").removeClass("cw-read-only"),CwZ(".cw-text-tip-edit > .noteDelete").removeClass("hideDeleteButton")):(CWDraw.drawMode=CWDrawMode.Drag,CwZ("#cw-pdfReader .cw-content").attr("class","cw-content cw-pointer-hand"),CwZ(".cw-tools .cw-selected,.cw-drawing-tools .cw-selected").removeClass("cw-selected"),CwZ('.cw-btn*[data-action="hand"]').addClass("cw-selected"),CwZ(".cw-property").hide());CWCommentManager.selectedComments&&CWCommentManager.selectedComments.isCurrentUser&&(CWCommentManager.selectedComments.decodedObj.comments=
CWCommentManager.annotationArr,CWCommentManager.selectedComments.decodedObj.deleted=CWCommentManager.deletedArr);CWCommentManager.selectedComments&&a&&a.id!==CWCommentManager.selectedComments.id&&(CWCommentManager.emptyList(),CWCommentManager.annotationArr=a.decodedObj.comments,CWCommentManager.deletedArr=a.decodedObj.deleted);CWCommentManager.selectedComments=a;CWCommentManager.selectedComments&&(CWDataCenter.isReadOnly=!CWCommentManager.selectedComments.isCurrentUser,a=CWCommentManager.selectedComments.decodedObj,
0<a.comments.length&&(CWCommentManager.annotationArr=a.comments),CWCommentManager.deletedArr=a.deleted,CWCommentManager.updateList())};e.prototype.getComments=function(){return CWCommentManager.annotationArr};e.prototype.getDummyData=function(){return{Colwiz:{Comment:[{mts:(new Date).getTime(),refId:CWDataCenter.fileId,uId:CWPDFReaderConfig.uId,uName:"My Annotations",commentsString:'{"List":{"MemberData":[{"data":{"Comments":[],"Graphics":[],"Deleted":[]}}]}}',isCurrentUser:!0}]}}};e.prototype.setDummyData=
function(b,d){CWDataCenter.comments[b.uId]=b;CWCommentManager.addUserToDD(b);CWCommentManager.initDDFunc();d&&CWCommentManager.setSelectedComments(b.uId)};e.prototype.getCommentsByPage=function(b){var d=[];if(CWCommentManager.annotationArr)for(var a=CWCommentManager.annotationArr,c=0;c<a.length;c++)a[c].page===b&&d.push(a[c]);return d};e.prototype.getCommentById=function(b){for(var d=CWCommentManager.annotationArr,a=0;a<d.length;a++)if(d[a].ID===b)return d[a]};e.prototype.addComment=function(b){try{null===
CWCommentManager.annotationArr&&(CWCommentManager.annotationArr=[]);CWCommentManager.annotationArr.push(b);CWCommentManager.commentSideBar.addComment(b);var d="",a;for(a in CWCommentManager.sidebarHtml)CWCommentManager.sidebarHtml.hasOwnProperty(a)&&(d+=CWCommentManager.sidebarHtml[a]);CwZ("#cw-antView ul.annsList").append(d);CWCommentManager.commentSideBar.bindEvents();CWCommentManager.sidebarHtml={};CwZ(document).trigger("cwAnnotationAdded",b);CWPDFReader.hasPendingChanges(!0)}catch(c){CWPDFReaderConfig.isCoreMode()||
CWPDFReaderConfig.isDesktopMode()?PDFRaven.captureException(c.stack):CwZ(document).trigger("cwExcToSentry",c)}};e.prototype.deleteShape=function(b,d,a){"undefined"===typeof d&&(d=!1);if(CWCommentManager.annotationArr){for(var c=CWCommentManager.annotationArr,e=0,e=0;e<c.length&&c[e].ID!==b;e++);c=a?[c[e]]:c.splice(e,1);0<c.length&&(CWCommentManager.commentSideBar.removeComment(c[0].ID),d&&CWDraw.deleteShapeByID(c[0].ID),a||(d=CWAnnotate.hashComment[c[0].ID],delete CWAnnotate.hashComment[c[0].ID],
delete CWAnnotate.hashSVG[d],CWCommentManager.deletedArr.push(c[0].ID)))}a||(CwZ(document).trigger("cwAnnotationRemoved",b),CwZ(document).trigger("cwAnnotationsUpdated"),CWPDFReader.hasPendingChanges(!0))};e.prototype.emptyList=function(){if(CWCommentManager.selectedComments&&CWCommentManager.selectedComments.decodedObj){var b=CWCommentManager.selectedComments.decodedObj.comments,d;for(d in b)CWCommentManager.deleteShape(b[d].ID,!0,!0)}CWAnnotate.hashSVG={};CWAnnotate.hashComment={}};e.prototype.updateList=
function(){for(var b=CWCommentManager.annotationArr,d=CWCommentManager.deletedArr,a=0;a<b.length;a++)if(CWCommentManager.commentSideBar.addComment(b[a],!1),a+1===b.length){var c="",e;for(e in CWCommentManager.sidebarHtml)CWCommentManager.sidebarHtml.hasOwnProperty(e)&&(c+=CWCommentManager.sidebarHtml[e]);CwZ("#cw-antView ul.annsList").append(c);CWCommentManager.commentSideBar.bindEvents();CwZ("#cw-antView ul.annsList>li").sort(CWCommentManager.commentSideBar.sortComments).appendTo(CWCommentManager.commentSideBar.commentList);
CWCommentManager.sidebarHtml={}}for(c=0;c<d.length;c++)for(CWCommentManager.removeComment(d[c]),a=0;a<b.length;a++)CWCommentManager.annotationArr[a].ID===d[c]&&CWCommentManager.annotationArr.splice(a,0)};e.prototype.removeComment=function(b){CWCommentManager.commentSideBar.removeComment(b);CWDraw.deleteShapeByID(b)};return e}(),CWSideBar=function(){function e(){this.bUserTyping=!1;this.commentList=null;this.isSetTimer=!1;this.numberOfComments=0}e.prototype.showInfoTip=function(){0===CwZ("#cw-antView ul.annsList>li").length&&
CwZ("#cw-antView .cw-anno-info").show()};e.prototype.addComment=function(b,d){void 0===d&&(d=!0);var a=CwZ("#cw-antView .cw-anno-info");a.is(":visible")&&a.hide();this.commentList||(this.commentList=CwZ("#cw-antView ul.annsList"));b&&(CwZ(".noAnnotations").hide(),(a=this.commentList.find("#"+b.ID))&&a.remove(),a=this.getMinY(b),a={cmtId:b.ID,cmtText:this.getCommentText(b),cmtClass:this.getCommentItemClass(b),timeDiff:CWUtils.timeDifference(b.ts,""),cmtPage:b.page,minY:a},a=CWHtmlStructure.getCommentBody(a),
CWCommentManager.sidebarHtml[b.ID]||(CWCommentManager.sidebarHtml[b.ID]=a),this.refreshCommentsTime(),d?(CwZ(".cw-tabContainer #cw-antView"),a=CwZ("#"+b.ID),b.cmt=this.getCommentText(b).replace(/\s+/g," ").trim(),a=a.find("textarea").closest("li"),CwZ(document).trigger("cwAnnotationCommentUpdated",a,b),CwZ(document).trigger("cwAnnotationsUpdated")):CWAnnotate.drawShape(b))};e.prototype.bindEvents=function(){function b(a){var b=parseInt(a.find('[name="minY"]').val(),10),d=0,c=parseInt(a.find(".cmtPage > span").html(),
10);CWPageManager.getPageByIdx(c-1);d=(100>b?0:b-100)*CWPageManager.getActualZoom();CWPageManager.moveToPage(c,d,void 0,a)}var d=this,a=CwZ("#cw-antView ul.annsList li");autosize(a.find(".cmtTextArea"));a.off("mousedown").on("mousedown",function(a){a.isDefaultPrevented()||(a=CwZ(this),b(a))});a.find("div.cmtText").off("mouseover").on("mouseover",function(){CwZ(this).attr("title",CwZ(this).find("p").text())});a.find("div.cmtText").off("mousedown").on("mousedown",function(){if(!CWPDFReaderConfig.checkReaderMode("drive")||
!CWDataCenter.isReadOnly){var a=CwZ(this).closest("li");if(!a.is(".active")){a.addClass("active");b(a);var c=CwZ("p",a),e=CwZ("textarea",a),a=c.text();d.isDefaultText(a)?e.val(""):e.val(a);setTimeout(function(){c.hide();e.show().trigger("focus");autosize.update(e);e.css("overflow","visible");CwZ(document).trigger("cwAnnotationsUpdating")},50)}}});a.off("mouseenter").on("mouseenter",function(){var a=CwZ(this),b=CWCommentManager.getCommentById(a[0].id);CWDraw.hoverSVGComment(b.ID,b.page);a.addClass("hover")});
a.off("mouseleave").on("mouseleave",function(){var a=CwZ(this),b=CWCommentManager.getCommentById(a[0].id);CWDraw.hoverSVGComment(b.ID,b.page,!0);a.removeClass("hover")});var c=a.find("textarea");c.off("focus").on("focus",function(){CWPDFReaderConfig.checkReaderMode("drive")});var e=!1,g=!1;c.off("keydown").on("keydown",function(a){var b=CwZ(this);1E3<b.val().length?(b.val(b.val().substr(0,1E3)),autosize.update(b),a.preventDefault()):(CwZ(document).trigger("cwAnnotationsUpdating"),CWPDFReader.hasPendingChanges(!0));
g&&13===a.keyCode?(g=!1,b.val(b.val()+"\n")):13===a.keyCode&&(e=!0,setTimeout(function(){b.trigger("focusout")},100));17===a.keyCode&&(g=!0)});c.off("keyup").on("keyup",function(a){g=!1});c.off("focusout").on("focusout",function(a){var b=CwZ(this),c=b.closest("li");a=CWCommentManager.getCommentById(c[0].id);var g=c.find("p"),h=b.val(),t=a.cmt!==h||""===h;e&&(h=b.val(),h=h.substr(0,h.length-1),h=b.val(h).val(),e=!1);t&&(a.cmt=h,a.ts=(new Date).getTime());g.text(d.getCommentText(a,g.text()));CWDraw.updateShapeComment(a.ID,
h);t&&(CwZ(document).trigger("cwAnnotationCommentUpdated",c,a),CwZ(document).trigger("cwAnnotationsUpdated"));setTimeout(function(){b.hide();g.show();c.removeClass("active")},50)});a=a.find("a.cmtDelete");a.off("mousedown").on("mousedown",function(a){a.preventDefault()});a.off("click").on("click",function(a){CWDataHolder.canvasMStates.onShape=!1;CWPDFReaderConfig.checkReaderMode("drive")&&CWDataCenter.isReadOnly||(a=CwZ(this).closest("li"),CWCommentManager.deleteShape(a[0].id,!0))})};e.prototype.setHoverOnLiById=
function(b,d){this.commentList&&(d?this.commentList.find("#"+b).addClass("hover"):this.commentList.find("#"+b).removeClass("hover"))};e.prototype.selectLiById=function(b){this.commentList.find("#"+b).trigger("click")};e.prototype.sortComments=function(b,d){return parseInt(CwZ(b).find(".cmtPage span").html(),10)===parseInt(CwZ(d).find(".cmtPage span").html(),10)?parseInt(CwZ(b).find('[name="minY"]').val(),10)>parseInt(CwZ(d).find('[name="minY"]').val(),10)?1:-1:parseInt(CwZ(b).find(".cmtPage span").html(),
10)>parseInt(CwZ(d).find(".cmtPage span").html(),10)?1:-1};e.prototype.refreshCommentsTime=function(){this.isSetTimer||(setInterval(function(){CwZ("#cw-antView ul.annsList li").each(function(){var b=CwZ(this),d=CWCommentManager.getCommentById(b[0].id);d&&b.find(".cmtTime").html(CWUtils.timeDifference(d.ts,""))})},1E4),this.isSetTimer=!0)};e.prototype.removeComment=function(b){null!==this.commentList&&this.commentList.find("#"+b).remove();b=CwZ(".cw-antView>div.cw-tabContent>ul>li").length;0===b&&
CwZ(".noAnnotations").show();CwZ(".numberOfComments").html("Number Of Comments:"+b);var d=CwZ("#cw-antView .cw-anno-info");0===b&&d.is(":hidden")&&d.show()};e.prototype.getCommentItemClass=function(b){var d=CwZ("div.cw-tabContent>ul>li").length+1;CwZ(".numberOfComments").html("Number Of Comments:"+d);return b instanceof CWComment?"icon-comment":b instanceof CWRectangle?"icon-rectangle":b instanceof CWLine?"icon-line":b instanceof CWEllipse?"icon-oval":b instanceof CWArrow?"icon-arrow":b instanceof
CWHighlight?"icon-highlighter":b instanceof CWFreehand?"icon-pencil":b instanceof CWSelectionHL?"icon-highlighter":""};e.prototype.getCommentText=function(b,d){if(""!==b.cmt)return b.cmt;if(b instanceof CWComment)return"Write a comment here.";if(b instanceof CWRectangle)return"Rectangle";if(b instanceof CWLine)return"Line";if(b instanceof CWEllipse)return"Ellipse";if(b instanceof CWArrow)return"Arrow";if(b instanceof CWHighlight)return"Highlight";if(b instanceof CWFreehand)return"Freehand";if(b instanceof
CWSelectionHL){if(d&&""!==d)return b.cmt=d;var a=window.getSelection().toString()||CWAnnotate.clipboardText||CWDataHolder.ieSelectedText;return a&&0<a.length?a.trim():"Text Selection"}};e.prototype.getMinY=function(b){var d;if(b instanceof CWComment)d=b.point.y;else{d=b.points[0].y;for(var a=1;a<b.points.length;a++)b.points[a].y<d&&(d=b.points[a].y)}return d};e.prototype.isDefaultText=function(b){return"Write a comment here."===b||"Rectangle"===b||"Line"===b||"Ellipse"===b||"Arrow"===b||"Highlight"===
b||"Freehand"===b?!0:!1};return e}(),CWCommentManager=new CWCommentManagerClass;
