var CWHtmlStructureClass=function(){function b(){}return b.prototype.getBody=function(a,d){a=encodeURI(a);d=encodeURI(d);var c="cw-logo";CWPDFReaderConfig.readerMode===CWPDFReaderMode.Publisher&&(c="publisher-logo");var e="display:none;",h="";CWPDFReaderConfig.readerMode!==CWPDFReaderMode.Library&&CWPDFReaderConfig.readerMode!==CWPDFReaderMode.Drive&&(e="",h="display:none;");var b=CWPDFReaderConfig.readerMode===CWPDFReaderMode.Drive,g=CWPDFReaderConfig.readerMode!==CWPDFReaderMode.Library&&CWPDFReaderConfig.readerMode!==
CWPDFReaderMode.Drive;CwH.partials=CwH.templates;var k=CwH.templates.getBody;return k({smallCanvasClass:"",imageUrl:a,logoClass:c,modeDrive:b,modeNotDriveLibrary:g,fullscreenBtnStyle:e,restoreBtnStyle:h,CWPDFReaderConfig:{cwURL:CWPDFReaderConfig.cwURL,idURL:CWPDFReaderConfig.idURL},pdfUrl:d})},b.prototype.getCommentBody=function(a){return(CWPDFReaderConfig.isDesktopMode()||CWPDFReaderConfig.readerMode===CWPDFReaderMode.Chrome?CwH.templates.getCommentBody:window.parent.CwH.templates.getCommentBody)({cmtId:a.cmtId,
cmtText:a.cmtText,cmtClass:a.cmtClass,timeDiff:a.timeDiff,cmtPage:a.cmtPage,minY:a.minY})},b.prototype.getSplashScreen=function(a){CwH.partials=CwH.templates;var d=CwH.templates.getSplash,c=!CWPDFReaderConfig.isCoreMode();return d({classSpec:a,notCoreMode:c,loaderClass:c?"cw-loader":""})},b.prototype.getPopupBody=function(a,d){var c=CwH.templates.getPopupBody;return c({getRecHtml:a,contextCont:d})},b.prototype.getDownloadPopup=function(a,d){var c=JSON.parse(JSON.stringify(a));/^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=|[A-Za-z0-9+/]{4})([=]{1,2})?$/.test(c.title)&&
(c.title=Base64.decode(c.title));var e=btoa(c.pdfLink+"@@@0"),h=CwH.templates.getDownloadPopup;return h({metaData:c,encodedHash:e,publisherOpt:d})},b.prototype.getReferenceTip=function(a,d){var c=window.parent.CwH.templates.getReferenceTip,e={ref:a};d&&(e.tip=!0);return c(e)},b.prototype.getAuthorSideBarLi=function(a,d){1<a.pubs&&(a.pubsPlus=!0);1<a.coCount&&(a.coAuthPlus=!0);var c,e,h,b=1<d?"s":"";CwZ(".cw-authorTab .numberOfAuthors span").text(d+" Author"+b);a.nameInitials=(c=a.fullName,e=c.toUpperCase().split(/[\s.]+/),
h=1===e.length?e[0].charAt(0):e[0].charAt(0)+e[e.length-1].charAt(0),h);c=CWPDFReaderConfig.isDesktopMode()||CWPDFReaderConfig.readerMode===CWPDFReaderMode.Chrome?CwH.templates.getAuthorSideBarLi:window.parent.CwH.templates.getAuthorSideBarLi;e=CWPDFReaderConfig.cwURL;h=e+CWUtils.generateEntLinks(a.id,a.fullName,"199");return c({author:a,domainURL:e,authBaseURL:h})},b.prototype.getAuthorSidebarWidget=function(a,d,c,e){var b=CwH.templates.getAuthorSidebarWidget,f="https://"+cPDF.domain,g=f+CWUtils.generateEntLinks(d.id,
d.fullName,"199");return b({nameInitials:a,authLink:g,thisAuth:d,pubs:c,co_authors:e,author:d,domainURL:f})},b.prototype.getHead=function(a,d,c){var e="lib/jquery_ireader.js lib/raven.js lib/Blob.js lib/jDialog.js lib/jDialogFunc.js lib/pdf.js lib/svg.min.js lib/autosize.js lib/svg.filter.js lib/zlib_and_gzip.min.js lib/pdf_find_controller.js lib/tether.js extension/html_structure.js publisher/iframe_pub.js main/00_config.js main/01_logger.js main/02_cw_codec.js main/03_utilities.js /main/03b_pdfreader.js".split(" "),
b=[];switch(CWPDFReaderConfig.readerMode){case CWPDFReaderMode.Chrome:e.push("main/04a_pdfreader_chrome.js");break;case CWPDFReaderMode.Library:e.push("main/04a_pdfreader_library.js");break;case CWPDFReaderMode.Drive:e.push("main/04a_pdfreader_drive.js");break;case CWPDFReaderMode.Publisher:case CWPDFReaderMode.Webimporter:e.push("main/04a_pdfreader_publisher.js")}e.push("main/05_annotations.js");e.push("main/06_page.js");CWPDFReaderConfig.readerMode!==CWPDFReaderMode.Publisher&&e.push("main/07_datacenter.js");
e.push("main/08_textlayer.js");e.push("main/09_comments.js");e.push("main/10_shape.js");CWPDFReaderConfig.readerMode===CWPDFReaderMode.Chrome?b.push(window._colwizStylesPath_["webpdf/reader-chrome.css"].replace("webpdf/","")):(b.push(window._colwizStylesPath_["webpdf/reader-web.css"].replace("webpdf/","")),b.push(window._colwizStylesPath_["webpdf/csl.css"].replace("webpdf/","")));var f=CwH.templates.getHead;return f({scripts:e,css:b,jsPath:a,cssPath:d,version:c})},b.prototype.getSignupDialog=function(){return(CWPDFReaderConfig.isDesktopMode()||
CWPDFReaderConfig.readerMode===CWPDFReaderMode.Chrome?CwH.templates.getSignupDialog:window.parent.CwH.templates.getSignupDialog)({})},b.prototype.getFeedbackForm=function(){return(CWPDFReaderConfig.isDesktopMode()||CWPDFReaderConfig.readerMode===CWPDFReaderMode.Chrome?CwH.templates.getFeedbackForm:window.parent.CwH.templates.getFeedbackForm)({})},b.prototype.getUserToDD=function(a,d){return(CWPDFReaderConfig.isDesktopMode()||CWPDFReaderConfig.readerMode===CWPDFReaderMode.Chrome?CwH.templates.getUserToDD:
window.parent.CwH.templates.getUserToDD)({uid:a,divText:d})},b.prototype.getCoreDialog=function(){return(CWPDFReaderConfig.isDesktopMode()||CWPDFReaderConfig.readerMode===CWPDFReaderMode.Chrome?CwH.templates.getCoreDialog:window.parent.CwH.templates.getCoreDialog)({})},b.prototype.getSupplementLiHtml=function(a,d){return(CWPDFReaderConfig.isDesktopMode()||CWPDFReaderConfig.readerMode===CWPDFReaderMode.Chrome?CwH.templates.getSupplementLiHtml:window.parent.CwH.templates.getSupplementLiHtml)({key:a,
finalFile:d})},b.prototype.insertButtonsOnPage=function(a){if(CWPDFReader&&CWPDFReader.pubSolInjected)return!0;if(CWPDFReaderConfig&&CWPDFReaderConfig.readerMode===CWPDFReaderMode.Webimporter)return"";var d,c="hidden"!==CwZ.trim(a["class"]),e="",b=!1,f=!1,g=!1;if(publisher&&(publisher.id,b=!!~a["class"].trim().indexOf("-list"),f=!!~a["class"].trim().indexOf("-detail"),d=publisher.buttonStyle,g=(b||f)&&"popup"===d),c)if("popup"===d)if(0===CwZ("#preloadCwZSprite").length&&CwZ("body").append('<div id="preloadCwZSprite"></div>'),
f)try{return a.buttonCB(a.metaData),!1}catch(k){return!1}else{if(b)try{return a.buttonCB(a.metaData),!1}catch(n){return!1}}else{CWPDFReaderConfig.newExtMode;e=!0;d="View & Annotate PDF";b="Add to wizdom.ai";a||(a={pdfUrl:"",index:0,inline:!1,"class":""});"undefined"!=typeof CWPDFReader_Publisher&&CWPDFReader_Publisher.getInstance().colwizOptions?e=CWPDFReader_Publisher.getInstance().colwizOptions.showAddToColwiz:CWPDFReader.colwizOptions&&(e=CWPDFReader.colwizOptions.showAddToColwiz);c="";CWPDFReaderConfig.readerMode===
CWPDFReaderMode.Webimporter&&(c='style="display:none !important"',b=CWPDFReaderConfig.pubModeBtnsTxt,d=b.view,b=b.add);CWPDFReaderConfig.readerMode===CWPDFReaderMode.Publisher&&(a["class"]+=" pub-mode",b=CWPDFReaderConfig.pubModeBtnsTxt,d=b.view,b=b.add);CWPDFReaderConfig.readerMode===CWPDFReaderMode.Chrome&&(d=CWPDFReaderConfig.extModeBtnsTxt.view);f="";a.inline&&!g&&(f=" cw-inline");f+=" "+a["class"];g&&(c='style="display:none"');var g=CWHtmlStructure.generateReaderHash(a.pdfUrl,a.index),m=CwH.templates.getButtons,
l="top";a.tooltipPos&&(l=a.tooltipPos);e=m({classes:f,style:c,generatedHash:g,index:a.index,url:a.pdfUrl,viewBtnTxt:d,hoverBtnText:CWPDFReaderConfig.pubModeBtnsTxt.viewHover,showAddButton:e,addBtnTxt:b,addHoverBtnText:CWPDFReaderConfig.pubModeBtnsTxt.addHover,tooltipPos:l});CWPDFReaderConfig.readerMode===CWPDFReaderMode.Chrome&&CwZ("base").length&&(e=e.replace(new RegExp(/href="(#[^"]*)"/),'href="'+location.href+"#"+g+'"'))}return e},b.prototype.generateReaderHash=function(a,b,c){a=a+"@@@"+b;return c&&
(a+="@@@forwarded"),a=Base64.encode(a),a},b.prototype.decodeReaderHash=function(a){a=Base64.decode(a).split("@@@");var b=[];return b.PDFURL=a[0],b.INDEX=a[1],a[2]&&"forwarded"===a[2]&&(b.FORWARDED=!0),b},b}(),CWHtmlStructure=new CWHtmlStructureClass;
"undefined"!=typeof CwH&&CwH.registerHelper("ifC",function(b,a,d,c){switch(a){case "==":return b==d?c.fn(this):c.inverse(this);case "===":return b===d?c.fn(this):c.inverse(this);case "<":return b<d?c.fn(this):c.inverse(this);case "<=":return b<=d?c.fn(this):c.inverse(this);case ">":return d<b?c.fn(this):c.inverse(this);case ">=":return d<=b?c.fn(this):c.inverse(this);case "&&":return b&&d?c.fn(this):c.inverse(this);case "||":return b||d?c.fn(this):c.inverse(this);default:return c.inverse(this)}});
